### ISSUE TITLE
Table formatting is missing

### ISSUE THREAD

**Issue by halindrome** [w3c/coga#1]
Throughout the document there are a number of tables (e.g., in section 2 Cognitive Function Table and Tags) and the tables have no formatting at all.  This makes it very hard to read, especially if the table is long and / or wide.

Please add some styling to the tables so there are at least borders.  If possible, style it such that the table heading remains on the screen as a reader scrolls through the table so the column meanings remain obvious.

**Comment by ehind67** [comment]
Tables are updated and have formatting in recent years. Closing as Fixed
