### ISSUE TITLE
Broken link in content usable doc

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#107]
There is a  broken reference link <https://docs.api.ai/docs/reminders-and-notifications> in section <https://www.w3.org/TR/coga-usable/#more-details-35>, it looks like the website moved their documents to other place, we could fix that in next updating working drat.

**Comment by lseeman** [comment]
Thank you for pointing this out.  We will check all links with link checker from https://validator.w3.org/checklink, to address this problem. 
We hope to have a new version by the 17th July at https://www.w3.org/TR/coga-usable/
Please feel free to review it again in a month and let us know if you have any more comments!

Thanks again

The Task Force
