### ISSUE TITLE
Change examples to active tense

### ISSUE THREAD

**Issue by rachaelbradley** [w3c/coga#116]
Consider whether to use Do/Don't instead of Use/Avoid. If changed, go through examples and change to active tense (Use…) to fit with the revised Do and Don’t. If not changed, review for language consistency. 

**Source:** Recommendation from the AG working group review.

**Comment by SteveALee** [comment]
+1 
I meant to mention this when we changed to active titles.

**Comment by lseeman** [comment]
do u want to add to editorial discusion and close?

**Comment by rachaelbradley** [comment]
This is complete.
