### ISSUE TITLE
Editorial suggestions

### ISSUE THREAD

**Issue by rachaelbradley** [w3c/coga#117]
Should Persona be plural in the headings?
Fix parallel structure in the lists in 5.2, 5.4.1, and 5.5

**Comment by rachaelbradley** [comment]
Changed Persona to Personas in section 6 and appendix a. Fixed lists in 5.2 and 5.4.1. I did not see a good way to resolve 5.5. See Editorial-Review-Issues-Fix branch.

**Comment by ruoxiran** [comment]
Fixed in PR #239
