### ISSUE TITLE
Summary headings and content

### ISSUE THREAD

**Issue by rachaelbradley** [w3c/coga#118]
Consider reworking the headings in Summary and reordering them Clear structure, clear design, clear content

Source: Suggestion from editorial review.

**Comment by SteveALee** [comment]
Nice idea. Also concider changing the content to put user need 1st in all cases

Also the last bullet `Test with real users!` should be pulled out as it is NOT a Objective and applies to ALL the objectives listed above it. 

See [this diffs](https://github.com/w3c/coga/compare/changes-from-ag-meeting-may-2020...steve-update-summary) but Lisa pointed out the added text is not correct.

**Comment by SteveALee** [comment]
Also @michael-n-cooper provided some example CSS to improve the look of the list.

**Comment by SteveALee** [comment]
I suggested some editorial changes 
https://github.com/w3c/coga/commit/ceafa8ceea30b923a1c54d4bceda168f0f1d6f06
https://github.com/w3c/coga/commit/32c2bfe9c34c935bfd3b44219258c4f1b83aea70

**Comment by lseeman** [comment]
do u want to add to editorial discusion and close?

**Comment by lseeman** [comment]
Many of  the objectives do not fit neatly. We may be able to rework them but that is a lot.
For example where would we put:  avoid mistakes, search, personalization and apis etc?
Can we move it to review for next version? This is a big thing

**Comment by jpascalides** [comment]
Thank you for your feedback. After discussion with the editorial group, we have decided to keep the existing heading structure as pursuing the action would require a mahor change to the document structure. We are updating the objectives.

**Comment by ruoxiran** [comment]
Fixed in PR #241
