### ISSUE TITLE
Ensure all information from the Abstract is included in the document

### ISSUE THREAD

**Issue by slhenry** [w3c/coga#119]
For example, in the main document where it has:
> The Objectives and Patterns presented here provide Supplemental Guidance beyond the current requirements of WCAG. They address accessibility barriers that could not be included in the normative WCAG 2.x specification and may not otherwise be addressed.

I think it should include the wording agreed upon for the abstract -- with some further simplification of language:
> The Objectives and Patterns in this document provide supplemental guidance beyond the current requirements of WCAG. Following this guidance is not required for conformance to WCAG. This guidance addresses accessibility barriers that could not be included in WCAG 2. Following this guidance will improve the accessibility for people with cognitive and learning disabilities.

**Comment by SteveALee** [comment]
also see #120

**Comment by rachaelbradley** [comment]
Closed per agreements in 25 January wordsmithing meeting. See https://github.com/w3c/coga/pull/236
