### ISSUE TITLE
minor copy edit suggestion

### ISSUE THREAD

**Issue by slhenry** [w3c/coga#120]
minor copy edit suggestion:

> The Objectives and Patterns presented here provide Supplemental Guidance beyond the requirements of WCAG. Following the guidance in this document is not required for conformance to WCAG. However, following this guidance will improve the accessibility for people with cognitive and learning disabilities.

to

> The Objectives and Patterns in this document provide supplemental guidance beyond the current requirements of WCAG. Following this guidance is not required for conformance to WCAG. However, following this guidance will improve accessibility for people with cognitive and learning disabilities.

**Comment by SteveALee** [comment]
Although we agreed that "Supplemental Guidance" is a proper noun now, without common knowledge or a definition I guess the general is better. It is almost self describing.

Note; similar text appears in two placsi nthe document.

**Comment by rachaelbradley** [comment]
Closed per agreements in 25 January wordsmithing meeting. See https://github.com/w3c/coga/pull/236
