### ISSUE TITLE
Consider dropping Appendix C and others

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#121]
- The document is very big as it is and the appendicies add extra bulk
- Appendix C is probably more than an appendix and would be better as a separate document

**Comment by lseeman** [comment]
please close

**Comment by SteveALee** [comment]
Not sure which Appendix exactly as they may have moved. Probably Policy makers.

**Comment by rachaelbradley** [comment]
Thank you for the suggestion. We discussed this at the December 10 COGA taskforce meeting and made updates rather than fully drop it. The appendix is now shorter and clearer.
