### ISSUE TITLE
Editorial suggestions in Introduction from Wordsmithing Meeting

### ISSUE THREAD

**Issue by rachaelbradley** [w3c/coga#122]
1. Consider changing "Making websites and applications that are **friendly** for people with cognitive impairments affects every part of design and development." to "Making websites and applications that are **usable** for people with cognitive impairments affects every part of design and development." Also discuss "to" vs "for". (NOTE: This is also in the Design Guide Introduction)

2. Consider whether "Often the issues that affect people with cognitive and learning disabilities include design, context, structure, language, usability, and other factors that are difficult to include in general guidelines." should be presented in list form.

3. Consider removing the bold from: Some design patterns create barriers for people with disabilities.  The patterns presented in this document have been designed to avoid such barriers for people with cognitive and learning disabilities. While this guidance may improve usability for all, these patterns are essential for some people **with cognitive and learning impairments** to be able to use content independently.  (NOTE: This is also in the Design Guide Introduction)

4. Consider changing "The Objectives and Patterns build on the:" to "The Objectives and Patterns build on prior work" or "The Objective and Patterns build on prior research by the COGA Task Force."

5. Consider switching the paragraph "Some design patterns create..." with "The objectives and patterns..."

**Comment by lseeman** [comment]
is this part of the discusions with wcag?

**Comment by rachaelbradley** [comment]
Yes.

**Comment by rachaelbradley** [comment]
Closed per agreements in 25 January wordsmithing meeting. See https://github.com/w3c/coga/pull/236
