### ISSUE TITLE
Persona diversity

### ISSUE THREAD

**Issue by eschafer** [w3c/coga#131]
https://www.w3.org/TR/coga-usable/

Thank you all for your work on this topic! I'm looking forward to reading through more in depth.

I'm concerned about how white and Eurocentric the personas seem to be. Does that also reflect the research that these guidelines are based on? If so, there should be a disclaimer for clarification. That just stood out to me as odd, especially within international guidelines.

**Comment by SteveALee** [comment]
Related to #135

**Comment by rachaelbradley** [comment]
Thank you for this suggestion. We have made these changes.
