### ISSUE TITLE
Update WAI Cognitive page to link to Content Usable

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#133]
https://www.w3.org/WAI/cognitive/

ASAP as we've been pointing people there

**Comment by lseeman** [comment]
I have not seen this page. Has anyone from COGA reviewed the content?

**Comment by SteveALee** [comment]
@lseeman just adding you as a reviewer and spotted you comment. Sorry I missed earlier

> I have not seen this page. Has anyone from COGA reviewed the content?

This was one of the pre existing pages we looked at a while back when prototyping [integrating more coga content](https://w3c.github.io/wai-coga/coga-draft/) into to the WAI site. This would be a good topic for the TF to revisit now we have content usable at Wide Review.

CC @rachaelbradley

**Comment by SteveALee** [comment]
See also https://github.com/w3c/wai-cognitive/pull/8 and https://github.com/w3c/wai-cognitive/pull/9

**Comment by SteveALee** [comment]
I closed the PR as @slhenry [updated the page](https://github.com/w3c/wai-cognitive/commit/8951f98efb586dc38782611b40cb6e8efd9ee541).

Will open a new issue for TF to review the page.

**Comment by slhenry** [comment]
@lseeman asked:
> Has anyone from COGA reviewed the content?

Yes. Got good input from COGA in the review before it was published. Here's a thread with some of COGA's input: https://lists.w3.org/Archives/Public/public-cognitive-a11y-tf/2019Mar/0035.html

:-)
