### ISSUE TITLE
Review Cognitive landing page on the WAI website

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#134]
This new issue opened as Lisa thought in #133 the WAI website [cognitive landing page](https://www.w3.org/WAI/cognitive/) could be reviewed by the TF,

Note: this page is a WAI staff page that the COGA TF have a particuar interest in.

**Comment by slhenry** [comment]
Looking forward to input on the idea to broaden this page or create an additional page.

See [Requirements Analysis for Cognitive Accessibility Introduction](https://github.com/w3c/wai-cognitive/wiki/Requirements-Analysis-for-Cognitive-Accessibility-Introduction). Thanks!

**Comment by lseeman** [comment]
Steve, can you close this issue? We have a different page and place for
action items. A

**Comment by SteveALee** [comment]
@lseeman Before closing this can we provide a link to that place showing this is still being tracked?

**Comment by lseeman** [comment]
Our planning page actions section. That is were we keep task force actions

**Comment by SteveALee** [comment]
Have added to the [Actions section](https://www.w3.org/WAI/GL/task-forces/coga/wiki/PlanningPage#Actions) of our planning page.

Note I see a disadvantage of the planning is that the contents disappear into the Wiki version history, whereas even closed issues are searchable. Also issues are easily open for public comment.
