### ISSUE TITLE
Use of Person First Language for Autism.

### ISSUE THREAD

**Issue by JamieKnightBBC** [w3c/coga#139]
I have reviewed the document here: https://www.w3.org/TR/coga-usable/ and noticed the document makes use of person first language (with autism, has autism) when referred to autistic people. 

Much like with the Blind and Deaf community, there is a well established norm of using identity first language (autistic) when referring to autistic people.

Sources:

NHS: https://www.england.nhs.uk/learning-disabilities/about/get-involved/involving-people/making-information-and-the-words-we-use-accessible/
NAS: https://www.autism.org.uk/get-involved/media-centre/how-to-talk.aspx
Research: https://www.autism.org.uk/describingautism, 
Advocacy groups: 
- ASAN (US) https://autisticadvocacy.org/about-asan/identity-first-language/
- AAA(Austrialia) https://www.autismawareness.com.au/resources-01/making-sense-of-language/

**Comment by SteveALee** [comment]
Purely for reference here is a [Twitter thread on the topic](https://twitter.com/GarethFW/status/1295660885147607040)

**Comment by JamieKnightBBC** [comment]
Good link. It's definitely related, but slightly different. ADHD community is different to Autism community. ADHD folks don't have an established identity first term yet, whereas autistic folks do.

**Comment by jpascalides** [comment]
Thank you for your thoughtful feedback. We will update the references to autism throughout the document to use identity-first language.
