### ISSUE TITLE
Review use of judgemental terms

### ISSUE THREAD

**Issue by JamieKnightBBC** [w3c/coga#140]
The document uses a few terms which come across as judgmental. I'd consider rephrasing to talk about impairment or a relevant measurable metric.

For example: 

3.2.2. use of the term "weak" 
"memory impairment, weak executive function and/or weak language processing skills"
would be better phrased as: "memory, executive function and/or language processing impairments"

4.7.5.3. use of term "strong"
"Without strong reasoning skills the user is likely to select the wrong menu option."

6.3.5 use of "bad"
"Anna has bad eye hand coordination"

3.4.2 use of "give up:
"As a user who often makes mistakes or touches the wrong thing, I want to be able to undo what I just did quickly and easily so that I can manage to use applications and not give up."

"Give up" might be a sensitive phrase for some people. It's often used in a negative way to imply someone is lazy or not trying hard enough.  In this scenario the user has been excluded or has become fatigued. Perhaps "so that I can manage to use applications before I become fatigued"

**Comment by StommePoes** [comment]
Suggestion: If "fatigued" could be made "tired" maybe? Fatigue is a higher-level medical vocabulary term, "tired" is a word we know what it means.

And if "tired" isn't quite right, another common-use word then.

**Comment by julierawe** [comment]
Hi, flagging a couple other terms that may come across as judgmental and suggesting possible alternatives:

3.3.3 User Story: "As a user does not understand numerical concepts"
Suggest replacing with “As a user who struggles with math concepts” or "“As a user who struggles to understand math concepts”

4.3.1.3 and 4.3.4.3: use of the term "low" 
Suggest replacing (in both sections) "People with low executive function, impaired memory, and other cognitive and learning disabilities" with "People with executive function and memory impairments and other cognitive and learning disabilities"

**Comment by rachaelbradley** [comment]
Thank you for these great suggestions. We have made the corrections.
