### ISSUE TITLE
Math Abbreviation 

### ISSUE THREAD

**Issue by JamieKnightBBC** [w3c/coga#141]
Not sure on this one, it might be a Jamie thing. I had to read carefully to work out if maths was short for "mathematical" the concept, to "math" the action.

**Comment by jpascalides** [comment]
Thank you for your suggestion! We will update the document to reference "mathematical" in parentheses after the first use of the word "math".

**Comment by ermi-ltd** [comment]
Perfect. Thanks for the feedback :)

**Comment by ruoxiran** [comment]
Fixed in PR #240
