### ISSUE TITLE
Appreciation 

### ISSUE THREAD

**Issue by JamieKnightBBC** [w3c/coga#142]
I haven’t finished reading the whole document yet but I wanted to leave a comment than it’s really flipping good. It’s clear and it’s a great resources I am already sharing with teams around the BBC.

Thanks for all the effort and energy to get it this far :)

**Comment by SteveALee** [comment]
Thank you Jamie! We'd love more detailed feedback if you have time.

**Comment by SteveALee** [comment]
Thank you for taking the time to raise those other issues.

**Comment by lseeman** [comment]
Thanks for all your help as well Jamie
