### ISSUE TITLE
Cognitive accessibility definition and other groups that benefit from it

### ISSUE THREAD

**Issue by plenainclusion** [w3c/coga#145]
We would like to suggest:

- Add a definition about cognitive accessibility
- Mention other groups that benefit from it.

I mean, not only people with cognitive and learning disabilities:

• People with acquired brain damage
• People with Attention Deficit Hyperactivity Disorder
• People with language disorders
• People with mental disorders
• Older people with cognitive problems associated with aging
• People in a situation of temporary stress
• People who do not know the language or culture of the country well
• People with limited technical knowledge

Even, sometimes children can be considered as a group that need it more than adults.

Thank you again for your work.

**Comment by rachaelbradley** [comment]
Thank you for the great suggestion. We have mentioned other groups that benefit from it, and have defined cognitive and learning disabilities.
