### ISSUE TITLE
Objective content is inconsistent

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#149]
Many of the Objectives have no text and others quite long text.

Currently the text acts as a bridge between the user stories and technical implementation details in the patterns.  That's excellent. However, as the Design Guide section is for Developers we could concider changing the focus and highlight what they should do and why it helps. 

For example in [Objective 5](https://www.w3.org/TR/coga-usable/#objective-5-help-users-to-maintain-focus-0) the text:

"Once users become distracted, they may find it difficult to remember what they were doing. Then they can no longer complete their task at all. This is especially problematic for users with both low attention and impaired memory, such as users with dementia. "

Could become:

"Aim to minimise the possibility of users being distracted from their objective by avoiding unsuitable content and behaviours.  Some may find it difficult to remember what they were doing after being iterrupted so provide reminders and enable them to easily continue to completion. 

It is also helpful to design tasks and content to be short and ensure users can collect all required information before starting."

That is less abstract and implementable, a key requirement.

I think Objectives could 

* Be sussinct
* Provide a summary of what to concider doing and why, in general terms for the objective.
* Not repeat details in the User Stories or Patterns
* Have just enough user requirements to make the reasons clear.

Quick links toObjectives:

* [Objective 1](https://www.w3.org/TR/coga-usable/#objective-1-help-users-understand-what-things-are-and-how-to-use-them-0)
* [Objective 2](https://www.w3.org/TR/coga-usable/#objective-2-help-users-find-what-they-need-0)
* [Objective 3](https://www.w3.org/TR/coga-usable/#objective-3-use-clear-and-understandable-content-0)
* [Objective 4](https://www.w3.org/TR/coga-usable/#objective-4-help-users-avoid-mistakes-or-correct-them-0)
* [Objective 5](https://www.w3.org/TR/coga-usable/#objective-5-help-users-to-maintain-focus-0)
* [Objective 6](https://www.w3.org/TR/coga-usable/#objective-6-ensure-processes-do-not-rely-on-memory-0)
* [Objective 7](https://www.w3.org/TR/coga-usable/#objective-7-provide-help-and-support-0)
* [Objective 8](https://www.w3.org/TR/coga-usable/#objective-8-support-adaptation-and-personalization-0)

**Comment by lseeman** [comment]
please close

**Comment by rachaelbradley** [comment]
Thank you for this great suggestion. We have created objective content based on this. I believe we have addressed this issue but please reopen if you disagree.
