### ISSUE TITLE
More Pattern examples

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#153]
There are several patterns that need more examples and others can be improved. We need a few examples (max 2 of each?) that clearly show 'good' and 'bad' user experiences according ot the patter. See [WAI tips](https://www.w3.org/WAI/tips/designing/) for possible ideas.

There is some possibly related work to find images for the Objectives.

**Comment by lseeman** [comment]
please close

**Comment by SteveALee** [comment]
Could be be done as part of pattern 'scrubbing' work

**Comment by lseeman** [comment]
i added them and you have reviewed. i think we can close this.

**Comment by rachaelbradley** [comment]
I believe this has been completed. Steve, please reopen this if you do not agree.
