### ISSUE TITLE
Editorial Pass on the Design Guide

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#154]
There's a lot of text in the 54 odd patterns and the opportunity for a good cleanup and checking for style, consistency, duplication and succinctness. 

# Why

* Significant part of Content Usable would benefit from a systematic review
* Improve for Designer and Developer audience
* Prepare for web version of Design Guide

See #167 for a worked example for Pattern **4.2.5 Clearly Identify Controls and Their Use**

# What

* Editorial fixes, minor and more substantial
* Better target developer audience
* Simplify the template (see below)
* Check relationships between patterns and content in wrong pattern
* Fill gaps in Objective text, Getting Started and Examples
* Add new Related Patterns and Related SCs Sections for web
* Possibly tweak user needs to better match patterns (separate exercise to review User stories?)

## Proposed simplified template for Patterns
 
From discussion in #167

1. User need
2. What to do
   - 1st paragraph: 1-2 sentences, with 1st sentence always starting with action verb. - current 'Description'
   - 2nd paragraph: "This can be achieved by:" followed by bulleted list of specifics - current'More details'
   - 3rd paragraph: "To get started," followed by short, very specific tip - current Getting Started'
3. How it helps: max of 4 short paragraphs
4. Examples: 2 x "Use" and 2 x "Avoid" in every pattern? Or maybe 2 for each, whenever possible?
5. Related Patterns: for Web version only, appear in side bar - max 3 
6. Related WCAG SCs as Related Patterns.

# How 

* Fit in with current review timeline, yet work on all Patterns
* Tracking Spreadsheet
* Task Force Reviews
* Phased so all Patterns kept to similar level of change at publication
   1. Template tweaks
   1. Editorial + audience adjustment
   1. Consistency and relationships
   1. Fill gaps in content

**Comment by SteveALee** [comment]
In general, after working through a few of the patterns, the types of changes I'm making are :

* Simple editorial
* More substatial rewording, especially to keep sussinct
* Removing text that is from another pattern
* Refocussing for developer audience
* Adding an optional section - Getting Started
* Updateing the examples
* Adding a new Related Patterns Link

I've worked in detail on **Pattern 4.2.5 Clearly Identify Controls and Their Use** by [making comments](https://docs.google.com/document/d/1nVTsmgts92i5_D7-oA9r87FxzXp_F9ndt_8mZ1aaM90/edit#heading=h.4c55r320ut16) in a google doc.  I've also provides an [example reworked pattern]() (the diffs made it impossible to read).

So how can I best present this type of Pattern work to the TF for review? I'd now like to work through all the patterns

**Comment by SteveALee** [comment]
Suggested Steps than could be done in phases on all patterns each iteration

1. Rename `Description` to be `What to Do` and refine to be a single paragraph clearly telling devs what the result should look like.
1. Rename More Details - clean up and prune hard - may be add more ideas in some cases
1. Merge More Details to follow 1st para of What To Do 
1. Ensure Getting Started contains ideas to get going, not just repeats of What to Do. Add to all?
1. Clean up Examples so they clearly decribe good and bad in dev terms with just enough "why"- fill in gaps
1. Add Relatted patterns and SCs sections in Asside for web version
1. Adjust some User Needs to more closely match the Patterns the yare included in. Splitting User Stories as required - may surface new patterns.

**Comment by lseeman** [comment]
please close

**Comment by SteveALee** [comment]
This has all been covered in our process now
