### ISSUE TITLE
Minor updates to Design Guide introduction

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#155]
I suggest the following changes to the [Design Guide introduction](https://www.w3.org/TR/coga-usable/#introduction)

"This guide is divided into design themes. Each theme includes user stories, testing methodologies, and design checkpoints. Simply understanding the themes and user stories may help designers make content more accessible to some users with cognitive and learning disabilities. "

* themes => objectives
* Should Objective and Patterns be capitalised throughout the document?
* I would also like to link to the summary from here for a easy overview of the Objectives. but see #138

**Comment by lseeman** [comment]
ISnt this part of the editorial list?
Having this as an issue mean we need an official response, before the final draft.
Do you want to close it and add it to the editorial list

**Comment by SteveALee** [comment]
Lets discuss in meeting - my understanding was everything in the list came via an issue

**Comment by SteveALee** [comment]
@lseeman OK I moved to our Google working document
