### ISSUE TITLE
Suggestion re User Stories About Findability, Searchability and Navigation

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#156]
These three user stories seem very similar. Possible to make clearer what the difference is between them? Or to consolidate?
- 3.2.1 Findable
- 3.2.2 Searchable 
- 3.2.3 Navigation

**Comment by rachaelbradley** [comment]
Thank you for your review and suggestion. These are related concepts. We originally had these three concepts combined into a single user story but broke them apart to make them clearer.
