### ISSUE TITLE
Suggested edits to 3.4.1 User Story: Assistance and support

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#158]
6th bullet: “I want inputs to accept different formats and not mark them as mistakes.” 
- This may not be possible in certain cases (e.g., when an app needs numbers, not text, to compute), so we suggest expanding this wording to "I want inputs to accept different formats and not mark them as mistakes or, if there is a mistake, I want a clear explanation on how to fix it."

8th bullet: “I want to use applications or APIs that help me, such as remembering my information so I do not need to enter it again and have help with my spelling.” 
- Suggest consolidating this bullet about not needing to enter my information again with the 14th bullet about wanting to save my work as I go/not have to start all over again.
- Suggest splitting the "help with my spelling" into a separate bullet 
- Suggest combining 8th and 14th bullets like this: "I want to use applications or API that saves all my work automatically so I don't have to start over again, which can create of cycle of reentering my data, and that allows me to save my information so I do not need to enter it again when I return to the site."

13th bullet: “I do not want a session to time out while I try to find the information needed, such as my postal/zip code or social security number.” 
- Because timeouts are often a requirement for security reasons, we suggest expanding to "I do not want a session to time out while I try to find the information needed, such as my postal/zip code or social security number. But if a session is going to time out for security reasons, I want to be notified with an appropriate amount of time beforehand and given the option to extend the session."

**Comment by rachaelbradley** [comment]
Thank you for your review and suggestions.  The current ability to meet a need does not change the user need. In some cases, you may not be able to meet it but the user need itself remains. Regarding consolidating items in bullet 8, these points are divided to map correctly to the rest of the document. While the sentences are in some cases longer than ideal, we are trying to keep to the standard structure of user needs and user stories in this section.
