### ISSUE TITLE
Provide a reference to language tags as the key means to achieve the goal of unambigous text formatting

### ISSUE THREAD

**Issue by fsasaki** [w3c/coga#160]
Details on "Pattern: Use Clear, Unambiguous Text Formatting and Punctuation"
https://www.w3.org/TR/2020/WD-coga-usable-20200717/#more-details-14

Especially for web content, language tags are the key means to achieve the goal of unambigous text formatting. Please mention this in the section 
https://www.w3.org/TR/2020/WD-coga-usable-20200717/#more-details-14
and provide a reference to BCP47.

**Comment by rachaelbradley** [comment]
Thank you for the great suggestion. We have made this addition.

**Comment by fsasaki** [comment]
Thank you very much for your response to our comment. We are satisfied with your resolution.
