### ISSUE TITLE
Suggested edits for 3.6.3 User Story: Voice Menus

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#165]
1. "As a slow speaker I want the system to wait for my response" 
- [ADD] and I want the choice of selecting an option by either using my voice or pushing a button.

2. "I want the best practices for usability to be followed."
- [ADD link to list of best practices for usability]

3. "As a user who struggles with multiple steps, I need to identify relevant options quickly."
- Clarification needed for what it meant by "identify relevant options quickly." The current emphasis on speed is a little confusing--would a user who struggles with multiple steps prefer single-stepped instruction instead of quick instruction?

4. Suggestions on how to reword judgmental terms in this section (see [issue #140](https://github.com/w3c/coga/issues/140)):
- "As a user who has memory impairments and weak language processing skills" --> "As a user who has memory impairments and difficulty processing language" 
- "As a user with low cognitive processing speed" --> "As a user who struggles with cognitive processing speed"
- "As a user who has weak executive function" --> "As a user with executive function impairment"
- "As a user with weak language skills" --> "As a user with language impairment" or "As a user who struggles with language processing"

**Comment by jpascalides** [comment]
Thank you for your suggestions. We have adjusted the language to avoid the use of judgmental terms. After some discussion, the group felt that the other suggestions were out of scope.
