### ISSUE TITLE
Suggested addition to 3.7.5 User Story: Task Management

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#168]
One suggested addition below:

I know how to start a task, and what is involved such as:

- the steps involved.
- [ADD] where I am in the task order and how many steps remain.
- a time estimate for completing the task and any time limits.
- and any materials I may need (such as a credit card number, passport number, questions that authenticate login such as “your mother’s maiden name”).
- There is support and instructions that I understand to help me organize the time and steps.
- Any limitations are clear to me before I begin.

**Comment by jpascalides** [comment]
Thank you for your thoughtful feedback. Task order has been addressed in a different pattern.
