### ISSUE TITLE
Four suggested changes to in 4.2. Objective 1: Help Users Understand What Things are and How to Use Them

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#170]
**(1) Third bullet in intro:** Suggest replacing "familiar terms" (which is subjective/depends on experience) and making a few other clarifications below:
- Current: “Text: Use familiar terms. For example, some people have a limited vocabulary. Uncommon terms may cause them difficulty.” 
- Suggested replacement: “Text: Use common terms and, when possible, words that have fewer syllables or a lower reading level. Some people have a limited vocabulary or may have trouble reading longer words. Uncommon or multisyllabic terms may cause them difficulty. For example, use “car” instead of “automobile” or “use” instead of “utilize.”
- Also, possible to provide links to lists of most common words in English and maybe 1 or 2 other languages?

**(2) 4.2.1.3 How it Helps:** Delete word in last paragraph:
"In another example, a user with Attention-Deficit/Hyperactivity Disorder is looking for information in a video. They can tell by the video title that this video [DELETE: is] has the information they need."

**(3) 4.2.1.4 More Details:** Clarify examples in last paragraph:
“When possible, provide information to help users understand how they got to the page. For example: breadcrumbs, clearly indicated on main navigation, highlighting currently selected tab, etc.)” 
What should be “clearly indicated on main navigation”--the breadcrumbs? If so, then remove comma between "breadcrumbs" and "clearly" or use parallel construction for the two examples: "For example: clearly indicating breadcrumbs on main navigation, highlighting currently selected tab, etc."

**(4) 4.2.7.4 More details:** Suggest adding a final bullet with guidance on whether/how to include alt text for symbols: 
- Use personalization semantics;
- Use clear and unambiguous symbols that can easily be seen and made larger;
- Be aware of cultural differences;
- In left-to-right languages, when adding a few symbols to a page place the image to the left of the text.
- When adding multiple symbols to a paragraph or section of text, place the symbols above the text.
- [ADD/CLARIFY] When adding symbols, should the alt text be empty or descriptive? What is WCAG guidance on this?

**Comment by jpascalides** [comment]
Thank you for your helpful suggestions. We have made changes to the document. Note that we do not feel text-to-speech can aid users who have difficulty read (regarding reading age). Our focus is on understandable content. Regarding alt text, we are trying not to overlap with WCAG.

**Comment by rachaelbradley** [comment]
Thank you for the great suggestions. The document has changed somewhat due to other's input but we have included most of these changes.
