### ISSUE TITLE
Four suggested changes to 4.4 Objective 3: Use Clear and Understandable Content

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#172]
(1) 4.4.1.2 Description: “Look at the most common 1500 words or phrases.” 
Suggest adding guidance on how users can identify the most common words in a particular language and/or to include link[s] to trusted resource[s] for the most common words in 1 or 2 languages. 

(2) 4.4.2 Pattern: Use a Simple Tense and Voice
This is a complex and nuanced concept. Links to additional resources and more examples may be helpful. 

(3) 4.4.11.2 Description: Consider adding caution about using decorative elements anywhere on the page, particularly those that are vibrant in color or motion. 
A site may have text against a solid, well contrasted background, but if there is visual "noise" on the side panels of the page, it may be distracting even if there’s no text overlaid on that particular section. Suggest adding a third bullet to this section:

For text:
- Use solid backgrounds for blocks of text.
- Use thick outlines with solid fills for text that is overlaid on background that has designs running through it.
- [ADD] Limit or avoid decorative elements anywhere on the page, particularly those that are vibrant in color or motion, that create visual "noise" that can make it hard to focus on text elsewhere on the page. 

(4) 4.4.13.1 "I find words easier to understand than digits."/Provide alternatives for numbers and numerical concepts.
The recommendation is to provide textual (word) alternatives to numbers. Would it also be appropriate to encourage using visual alternatives (with alt text)?

**Comment by jpascalides** [comment]
Thank you for your comments. The task force will avoid making these changes due to the potential impact on other types of disabilities as well as other significant impacts to the document.
