### ISSUE TITLE
Three suggested changes to 4.5. Objective 4: Help Users Avoid Mistakes or Correct Them

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#173]
(1) 4.5.5.3 How it Helps: Avoid use of "general population" and soften absolutist language ("cannot complete the task" -->  
- Current paragraph: "People with cognitive and learning impairments make many more mistakes filling out forms than the general population. When mistakes cannot be easily corrected they cannot complete the task." 
- Suggested replacement: "People with learning disabilities and cognitive impairments, including ones that are commonly associated with aging, may make many mistakes when filling out forms. When mistakes cannot be easily corrected, these users may have trouble completing the task." 

(2) 4.5.6.2 Description: "Use common words"
As noted in [#172](https://github.com/w3c/coga/issues/172), it would be great to link to trusted resource[s] for “common words”

(3) 4.5.7 Pattern: Use Clear Step-by-step Instructions
Suggest adding commentary about finding a balance between writing clear steps and getting too verbose. Often in breaking down steps into their most discrete pieces, the list of things to do ends up getting very lengthy, which may overwhelm for the user. Finding the balance between clear and concise is key.

**Comment by jpascalides** [comment]
Thank you for your feedback. Regarding #1, we will avoid making this change in this version of Content Usable but will consider the feedback for the next version. We are not able to add links to external resources regarding #2. Number 3 is addressed elsewhere in the document.
