### ISSUE TITLE
Suggest adding "attention" to wayfinding list in 4.8.6 Pattern: Provide Help with Directions

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#174]
In 4.8.6.3 How it Helps, suggest adding "attention" to this bulleted list:
"Wayfinding requires many cognitive functions so designs should accommodate a wide range of cognitive impairments including those supported by other Design Patterns. For example:
- memory,
- [ADD] attention,
- executive function,
- spatial orientation,
- visual/spatial attention, perception and processing,
- spatial disorientation anxiety,
- language processing
- intellectual"

Also, in the 1st paragraph in this section, suggest one change to make the clause about indoor navigation less absolute and more in line with outdoors clause:
"The help required to address wayfinding issues varies per individual and also between indoor navigation, where there [are --> can be] more stimuli, and outdoors, where there can be more demands on memory."

**Comment by jpascalides** [comment]
Thank you for your suggestion. We have added "attention" to the list in 4.8.6.
