### ISSUE TITLE
Two suggested changes to 5.4.1 Differences from Usability Testing with the General Population

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#175]
(1) Penultimate bullet: “The questions should not be too difficult.” 
Suggest replacing with more specific wording: "The questions should be short and use common words." 
Also suggest adding link to relevant COGA section about using/finding "common words"

(2) Suggest adding a last bullet: "Make clear that the tester can end the user testing session at any time." 
This isn’t a difference from testing with the general population but is an important reminder for users of the COGA guidelines.

**Comment by jpascalides** [comment]
Thank you for your helpful suggestions. We have addressed these considerations elsewhere in Content Usable.
