### ISSUE TITLE
Suggested corrections and edits for Summary section

### ISSUE THREAD

**Issue by KimPatch** [w3c/coga#176]
Here are a bunch of corrections and edits that make the summary more direct, succinct and clear:

1. Summary

1. Help users understand what page elements are and how to use them. Use symbols, terms and design patterns that are already familiar to users so they don’t have to learn new ones. People with cognitive disabilities often need predictable behavior and design patterns. For example, use the standard convention for hyperlinks (underlined and blue for unvisited; purple for visited).

2. Help users find what they need. Make navigating the system easy. Use a clear and easy-to-follow layout with visual cues such as symbols. Use clear headings, boundaries and regions to make it easy for users to understand the page.

3. Use clear text and images. Use simple words, short sentences, small blocks of text, clear images, and easy-to-understand video.

4. Support different ways to understand content. Use graphics, summarize long documents, include icons on headings and links, and provide alternatives for numbers.

5. Help users avoid mistakes. Use good design, which makes user errors less likely. Only ask the user for what you need! Make it easy to correct errors.

6. Help users maintain focus. Avoid distracting users from their tasks. Use headings and breadcrumbs (ways to go back to previous steps) so users can reorient and restore context if needed. Make breadcrumbs clickable so users can undo mistakes.

7. Reduce the need for users to rely on memory. Avoid barriers such as long passwords to log in, or voice menus that require users to remember specific numbers or terms. For difficult-to-avoid memory barriers, provide an easy option.

8. Make it easy to get human help and give feedback. If users have difficulty sending feedback, it’s hard to know if users can use the content or when they’re having problems.

9. Support adaptation and personalization. People with cognitive disabilities often use assistive add-ons or extensions. Extensions that use personalization can make it easy for a user who needs extra support to simply to select alternative options. Support personalization when you can. Don’t disable add-ons and extensions!

10. Test with real users! Involve people with disabilities in the research, design and development process. They're the experts in what works for them. Involve people with cognitive and learning disabilities in several ways: 
- Focus groups
- Usability tests
- The design and research team

**Comment by SteveALee** [comment]
See also #138

**Comment by rachaelbradley** [comment]
Thank you for the great suggestions. We have made many of these though not all of them.
