### ISSUE TITLE
Suggested changes to the Anna (dyslexia) persona and scenarios

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#177]
(1) Intro: 
Suggest expanding description of core issues with dyslexia, narrowing emphasis on numbers/digits, clarifying or replacing "auditory discrimination," and replacing judgmental wording
- Current wording: "She has moderate dyslexia, which affects her ability to read, spell and use numbers. Anna has a poor working memory, especially for numbers and digits. She also has poor auditory discrimination which affects her ability to read quickly."
- Re numbers/digits: We suggest avoiding broad description about Anna having trouble "using numbers." Trouble with numbers is not a core issue with dyslexia. It's not uncommon for people with dyslexia to also have dyscalculia, but it's best to avoid conflating the two. Our suggestion below includes a very specific way people with dyslexia struggle with numbers. 
- Re "auditory discrimination": Typically this term is used to describe people who have trouble understanding the words they _hear_. This can contribute to but is not a core aspect of dyslexia--research indicates the core difficulty with dyslexia is trouble understanding how the sounds in words are represented by letters. Because many people with dyslexia rely on their listening skills to help work around their difficulty with reading (e.g., using text-to-speech), we suggest replacing "auditory discrimination" or else clarifying how Anna's difficulty listening to speech affects her ability to read.
- Suggested rewording: "She has moderate dyslexia, which affects her ability to read and spell. Anna reads slowly and has trouble 'sounding out' many words, including very common ones. She also struggles with working memory and often mixes up the order of letters in words and the order of digits in things like phone numbers and passwords."

(2) 6.3.1 Anna Scenario 1: Logging In: 
Suggest making the sequence of events clearer
- Current wording: "Anna's use of the library catalogue from home failed at the first attempt when she could not remember her password. She kept putting in ‘afib61’ rather than ‘afid16’ and could not see the mistake. The error message on the web page had not helped because it announced that her user name or password were incorrect and she was not sure which one was wrong. Luckily, as she was on her own laptop the browser settings allowed her to save her password and she was able to automatically log in."
- Logical sequence: If she had already saved her login info in the browser settings on her laptop, why does this scenario start with her trying to manually enter this info rather than it auto-populating? We suggest specifying that Anna had to reset her username and password midway through this scenario and that when she did this, she saved the new info so she could automatically log in the next time. 
- Also suggest replacing "could not see" with "did not notice" (to avoid common myth that dyslexia is a problem with vision)
- Suggested wording: "Anna tried to log into the library catalogue from home but got an error message. She didn't notice that she had put in ‘afib61’  for her password rather than ‘afid16.' And since the error message said that her user name or password were incorrect, she wasn't sure which one was wrong. She ended up resetting both and saving the new information in the browser settings on her laptop. The next time she used her laptop to access the library catalogue, she was able to log in automatically."

(3) 6.3.4 Anna Scenario 4: Overlooking Important Information
Suggest clarifying that Anna's listening troubles are separate from her reading troubles and that she finds her screen reader helpful but can't listen to it at faster speed.
- Current wording: "Anna is a very slow reader and often sounds out words. She has low auditory processing skills so she cannot speed up her screen reader. Therefore, to manage her busy life she has to try and scan read and skip through the massive amounts of content, emails and newsletter she sees so she can read only the most important parts."
- Suggested rewording: "Anna's text-to-speech app is a big help. But in addition to having dyslexia, she also struggles with auditory discrimination. This means she has trouble processing the words she hears so she can't speed up her screen reader. As a result, it can take her a long time to listen to lengthy documents. Therefore, to manage her busy life, she tries to scan things like emails and newsletters, skipping massive amounts of text as she tries to focus on only the most important parts."

(4) Consider adding a scenario about fonts, colors, busy layouts
- The current guidelines note that Anna's 3rd scenario was adapted from MOOCAP Erasmus + Persona CC-BY-4.0 http://gpii.eu/moocap/?page_id=33). That source also has the following paragraph about fonts and colors:
- "Anna finds many pages of information that she is interested in, but some she simply cannot use, as she cannot read them well enough.  She has set her browser to display web pages with brown text on a sepia background, but many websites override these preferences and present the text in other colour combinations that are much harder for Anna to read.  In addition, if pages have patterned backgrounds, very busy layouts or worse still, moving banners, Anna finds them too difficult to read.  If there is a moving banner, she will hold up a piece of cardboard to cover it over (she carries a collection of different sizes and shapes of cardboard in her handbag for this purpose).  But if the presentation of the page is too difficult, she will try to copy the text into a Word document for easier reading, or simply give up on the page."
- This source was published several years ago, before there was a lot of interest in "dyslexia fonts." We suspect users may search the COGA guidelines for "dyslexia fonts," and an Anna scenario might be a good place to add a sentence about how she prefers the way some fonts look, finding certain fonts easier to read than others, etc. 

(5) 6.3.5 Scenario 5: Pressing the Correct Button
Suggest replacing judgmental wording: "Anna has bad eye hand coordination" --> "Anna struggles with eye hand coordination"

**Comment by rachaelbradley** [comment]
Thank you for your suggestions. We made many of these changes. The current editorial version is at https://raw.githack.com/w3c/coga/consistency_checks/content-usable/index.html#tal-a-student-who-has-dyslexia-and-impaired-eye-hand-coordination
