### ISSUE TITLE
Suggested changes to the Carolyn (ADHD) persona and scenarios

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#178]
(1) Intro:
- Add "executive function" since it's such a big part of ADHD and since "executive function impairment" is used so often throughout the guidelines
- Clarify what is meant by "She knew she could cope with the studies" 
- Clarify that the psychologist diagnosed her with ADHD, not just mentioned it
- Use same name and styling of ADHD so it's consistent throughout the COGA guidelines; the American Psychiatric Association, whose diagnostic manual (the DSM-5) is widely used/respected, the styling includes a hyphen and slash mark: "attention-deficit/hyperactivity disorder"
- Suggested rewording in brackets: "Carolyn found concentrating at school difficult and when she got into college [[to take --> and started taking]] a course in business studies life became even more stressful. She knew she could [[cope with the studies --> understand the material]] but never seemed to get her work completed on time, found it hard to start a report and even to create a plan for a project. When working with others she always had good ideas but somehow they were never taken up and she became frustrated often failing to keep her feelings in check. Luckily, a tutor suggested she [[sought --> seek]] help and when a psychologist [[, mentioned --> diagnosed her with]] Attention-Deficit/Hyperactivity Disorder (ADHD) Carolyn was relieved to have a reason for [[some of the planning and organizational difficulties she was having --> her planning and organizational difficulties and other executive function impairments]]. She learnt that if she could make use of her constantly active brain and body as well as manage her time better, she could turn her hobby into a very successful Yoga business.

(2) 6.4.1 Carolyn Scenario 1: Gathering Key Points from a Heavy Text Based Document or Web Page
- Improve logical flow from intro to 1st scenario: intro says a psychologist talked to her about ADHD and she is relieved to know why she is struggling with organization and planning, but 1st scenario currently starts with her not connecting common ADHD symptoms to her ADHD
- Avoid near-repeat of "lost" and "lose" in same sentence and near-repeat of "clear" and "clarity" in same sentence
- Reword sentence about "using her mobile" so it's clear she's reading (rather than talking or texting) when she encounters advertisements 
- Clarify what is meant by "content list" and "recognizable icons linking to simple bold text clarifying the important points"
- Current wording: "Carolyn could not really explain her apparent forgetfulness and not being able to focus or complete tasks, but she knew that if she came across a long document or web page with dense text she had to find the key points. If the web page failed to have a clear structure with a content list, well-spaced and highlighted headings she would be lost and lose concentration. Carolyn also said that if she was using her mobile she found advertisements appearing between chunks of text completely upset her focus and she had to stop reading. However, when there was good use of white space, recognizable icons linking to simple bold text clarifying the important points, Carolyn could target these areas and find out what she needed. A clear summary also provided clarity of understanding and Carolyn could remember much of what she had read."
- Suggested rewording: "Before she was diagnosed with ADHD, Carolyn couldn't explain her forgetfulness or her trouble with staying focused or completing tasks. But she knew that if she came across a long document or web page with dense text, she had to work really hard to find the key points. If the web page didn't have a clear structure that listed all of the sections at the top and that had well-spaced and highlighted headings throughout the article, she would lose concentration. Carolyn also knew that if she was reading on her mobile, any advertisements that appeared between chunks of text would destroy her focus and she'd have to stop reading. However, when there was good use of white space, simple bold text and recognizable icons linking drawing attention to important points, Carolyn could target these areas and find out what she needed. A clear summary also helped Carolyn understand and remember much of what she had read."

(3) 6.4.2 Carolyn Scenario 2: The Power to Stop Scrolling Carousels and Banners
- Reword scenario title so it follows same style as the others (i.e., starting with a gerund): "Stopping carousels and banners from scrolling"
- Remind users early in this scenario that Carolyn is setting up a website involving yoga 
- Reword "real content" to avoid making it sound like the carousel and banner aren't "real" parts of the site
- Clarify last 2 sentences, including making clearer who her intended audience is
- Current wording: "When setting up a new website for her business, Carolyn found an attractive template with several different ways of being able to show images of her exercises. However, she could not make the carousel of photographs pause, or a banner with her latest news stop scrolling. This really annoyed her as she found both items stopped her concentrating on the real content on the rest of the site. She thought that if it was upsetting her, what about her intended audience! She had to find a friend to add some code that not only added controls, but also stopped the automatic movement giving her website a calmness that she hoped her yoga teaching achieved."
- Suggested rewording: "When setting up a new website for her yoga business, Carolyn found an attractive template with several different ways of showing images of her exercises. However, she could not make the carousel of photographs pause, or make the banner with her latest news stop scrolling. This really annoyed her as she found both items made it hard for her concentrate on any other parts of the website. She worried that if the site looked hectic and distracting, it would be especially unappealing to customers seeking a calm place to learn about yoga. She asked a friend to add some code so she could stop the automatic movement and make her website feel as peaceful as one of her yoga classes."

(4) 6.4.4 Carolyn Scenario 4: Learning Information from a Video
- Reword to reduce repetition of "a few minutes" as well as concentrate/concentration 
- Suggest adding last sentence about using transcript to help find key sections of the video
- Current wording: "Theoretically, Carolyn likes instructional videos, but in practice she can only concentrate well enough to learn for a few minutes at a time. Then she loses her concentration. She will usually lose focus earlier if there is more than a minute of content that she already knows. When this happens, she misses the information that she needs! Carolyn tries hard but she still cannot focus for more than a few minutes on content that she already knows. Sometimes she watches videos at high speed so that they are less boring for her, but she still loses focus within a few minutes. When a video is broken down into segments with clear headings, she can jump to the information she needs to learn, and jump forward over segments that she already knows. When she misses information that she needs she can easily jump to the correct location and focus."
- Suggested rewording: "Carolyn likes watching instructional videos, but starts to lose focus after a few minutes. It's especially hard for her to concentrate if there is more than a minute of content that she already knows. Sometimes she watches videos at high speed to try to make them less boring, but she still quickly loses focus and has trouble locating information she missed. When a video is broken down into segments with clear headings, she can skip the segments she already knows and jump to a section she needs to focus on. Whenever a video transcript is available, she likes to search it for key terms. Watching the video and reading parts of the transcript help her learn new information."

**Comment by rachaelbradley** [comment]
Draft response: Thank you for the detailed and helpful suggestions. We included most of them. The few we did not include were because they changed the intent or caused plain language issues.  We really appreciate the thought feedback.
