### ISSUE TITLE
Suggestions re icons and other aspects of the summary 

### ISSUE THREAD

**Issue by julierawe** [w3c/coga#180]
My Understood colleagues and I liked seeing icons in the summary and wanted to suggest:

**(1) Weaving the icons throughout the report:** It's our understanding that these icons currently only appear in the summary, but we see a benefit to using them in other parts of the guidelines, especially if there is just one icon for each of the eight objectives. We suggest showing the relevant icon in:
- The beginning of each objective in sections 3 and 4
- Appendix A
- The new "Relevant Patterns" section you're considering adding to each pattern. Using icons in "Relevant Patterns" could be especially helpful if one of your goals is to point users' attention to patterns that appear in different objectives. (See [#167.](https://github.com/w3c/coga/issues/167)) 

**(2) Making some of the icons easier to understand:** We really like the magnifying glass (2nd in the list) and the question-and-answer text bubbles (8th in the list). But we wanted to suggest alternatives for some of the other icons that are more abstract/less familiar:
- 1st item in the list: Help users understand what things are and how to use them: Instead of hamburger menu leaning to the side (to look like steps/stairs?), suggest showing a lightbulb or perhaps a finger pressing button
- 3rd item: Help users understand with clear text and images: Instead of grid of black squares, suggest icon of device showing web page with a few lines of text and solid shapes for images, perhaps similar to this: https://www.onlinewebfonts.com/icon/395989
- 4th item: Provide support for different ways to understand content: Is this a second entry for Objective 3 (Use clear and understandable content)? If you're keeping this as a separate item in the summary, suggest replacing the icon that currently has two different types of charts/graphs with an icon that shows just one type of chart, possibly a bar graph with an arrow, like this: https://thenounproject.com/term/bar-graph/128637/
- 5th item: Help users avoid mistakes: Instead of a canister of spilled liquid, suggest showing a big X inside a circle
- 7th item: Ensure processes do not rely on memory: Instead of arrow pointing to vertical line, suggest showing thought bubble
- 9th item: Support adaptation and personalization: The current icon might work well at a larger size, but at current size the arrows in particular are hard to see. Suggest instead a big cog with a checkmark inside, perhaps like this: https://www.dreamstime.com/cog-check-icon-check-mark-gear-cog-check-icon-check-mark-gear-vector-illustration-white-background-image139070138

**(3) Aligning the numbered items in the summary with the objectives in the guidelines:** As noted above, it looks there are currently two numbered items about the 3rd objective (Use clear and understandable content), plus a 10th item about user testing. If you want to keep the current set of 10 items, maybe drop the numbers from the summary?

**(4) Adding internal links to the boldface phrases in the summary:** It might be helpful if users could easily jump from the summary to corresponding sections of the guidelines.

**(5) Adding a sentence/link to the appendix mapping user needs, persona and patterns:** My Understood colleagues and I think Appendix A is a really helpful overview that includes a nice amount of detail about how the guidelines fit together. Because the summary is likely to be the first thing that many people read, we suggest adding a sentence at the end of the summary that says something like, "For a more detailed overview, go to the appendix that maps design objectives to user needs and personas."

**Comment by slhenry** [comment]
Several of these relate to input from the Accessibility Education and Outreach Working Group in the document attached to https://lists.w3.org/Archives/Public/public-cognitive-a11y-tf/2020Sep/0005.html

**Comment by rachaelbradley** [comment]
Thank you for the great suggestion. We will have made these changes.
