### ISSUE TITLE
[minor] match outline numbering with Objective numbering

### ISSUE THREAD

**Issue by slhenry** [w3c/coga#181]
The Objectives headings are numbered, e.g., "1":
> Objective 1: Help Users Understand What Things are and How to Use Them

In some sections, the numbering matches, e.g., "3.1" and "Objective 1":
> 3.1 Objective 1: Help Users Understand What Things are and How to Use Them

In other sections, it does not, e.g., "4.2" and "Objective 1":
> 4.2 Objective 1: Help Users Understand What Things are and How to Use Them 

It would be easier if the numbering matched. e.g., remove the subheading for "4.1 Design Guide Introduction".

**Comment by rachaelbradley** [comment]
Thank you for your suggestion. This has been changed in branch 15_February_Issues and will be merged before publication.

**Comment by ruoxiran** [comment]
Fixed in PR #239
