### ISSUE TITLE
Plain language - Passive sentences

### ISSUE THREAD

**Issue by martynka** [w3c/coga#182]
1.  Many sentences are written in passive voice. They are hard to understand. I need to stop and analyze the meaning. Some examples include: 
"Overall, by addressing barriers to accessibility for users with cognitive and learning disabilities, improvements to digital technologies can be achieved and there is the potential to improve user experience for everyone."

"Some aspects of making web content and applications friendly for people with cognitive and learning disabilities are best dealt with as part of the overall design process. For most organizations there should be scope included for a user-centered design process."

"If people with cognitive impairments are included in the usability testing and their feedback is accounted for, the website will be easier to use for everyone, including people who are experiencing stress or mental health issues."

"User needs for people with learning and cognitive disabilities (COGA) are often helpful for other users, although they can usually manage to use the site without these user needs being met."

"As a user with a memory impairment, attention impairment and/or executive function impairment or as a user with a communication disability who uses symbols, I need to know the purpose of the content so that I know if I am in the right place, and what I am doing even if I lose attention and focus for a time."

Check more text and improve on it.

**Comment by rachaelbradley** [comment]
Thank you for the great suggestion. We have fixed these issues and conducted several plain lanugage edits in addition.
