### ISSUE TITLE
Repeated words (text typos)

### ISSUE THREAD

**Issue by martynka** [w3c/coga#183]
1. The 7th bullet under: "3.8.1 User Story: Adapt" repeats "I need" twice:
"When I do not know a word I need I need the symbols and pictures that I know and recognize."

2. The second sentence in the second paragraph under the "4. Design Guide"  repeats "not" twice: "They are intended to address barriers that could not not be included in the normative WCAG 2.x specification and may not otherwise be addressed."

**Comment by nitish-awasthi** [comment]
I want to work on this issue!!
Please assign me for this task.

**Comment by nitish-awasthi** [comment]
@lseeman How can I work on this?

**Comment by rachaelbradley** [comment]
Thank you for the great suggestion. We have fixed the first change in http://raw.githack.com/w3c/coga/master/content-usable/index.html and the second in the 15_February_Issues branch.  We will merge this before publishing.

**Comment by ruoxiran** [comment]
Fixed in PR #239
