### ISSUE TITLE
4.2.2.4 More Details - typo

### ISSUE THREAD

**Issue by martynka** [w3c/coga#184]
The second bullet under the 4.2.2.4, the --- such as ---- should be removed. 
"Uses common design patterns, such as are documented in the ARIA authoring best practices or are used in the most popular sites:"

**Comment by rachaelbradley** [comment]
DRAFT Response (Needs taskforce approval): Thank you for taking the time to poin this out. This sentence needed reworking. After review, we changed this to "Common design patterns, such as those documented in the ARIA  authoring best practices or used in the most popular sites:"

**Comment by ruoxiran** [comment]
Fixed in PR #239
