### ISSUE TITLE
4.3.3.3 How it Helps (repeated text and unnecessary text)

### ISSUE THREAD

**Issue by martynka** [w3c/coga#185]
The last sentence  in the second paragraph under the 4.3.3.3 section, has repeated text "impact problem solving skills" and unnecessary text: "those that":

"Clear layout helps people with cognitive and learning disabilities that impact problem solving skills, get overwhelmed when presented with a lot of text, **impact problem solving skills**, **those that** and those with difficulties with more complicated tasks"

**Comment by rachaelbradley** [comment]
DRAFT response (Needs taskforce approval): Thank you for taking the time to point this out. We have made this correction.
