### ISSUE TITLE
4.4.5.3 How it Helps (ADD)

### ISSUE THREAD

**Issue by martynka** [w3c/coga#188]
Found one occurrence of ADD, where it should be written ADHD instead.
Under the section "4.4.5.3 How it Helps", first sentence in the second paragraph:

"Example: A graduate student with ADD may need to teach themselves a new software skill. "

**Comment by rachaelbradley** [comment]
DRAFT response (Needs approval): Thank you for pointing out this error. During the glossary process we decided to reference this as Attention Deficit (hyperactivity) disorder, AD(H)D. We have updated this example and any of ADHD to AD(H)D.

**Comment by martynka** [comment]
This sounds great. Thank you. 
In my view this is resolved and can be closed.
