### ISSUE TITLE
4.4.9.3 How it Helps (don't understand sentence, may need punctuation)

### ISSUE THREAD

**Issue by martynka** [w3c/coga#189]
Under the "4.4.9.3 How it Helps" section, second sentence in the second paragraph may need punctuation:

I don't understand this sentence, it's confusing: 
"If they need to remember what they are doing, divide the steps and track what they have done they are much more likely to make mistakes."

The above sentence need punctuation. Is this supposed to be the meaning of the above sentence:
"If they need to remember what they are doing, divide the steps, and track what they have done, they are much more likely to make mistakes."

Here is the full paragraph:
"For example, a person with a low working memory cannot hold onto many pieces of information at the same time. If they need to remember what they are doing, divide the steps and track what they have done they are much more likely to make mistakes. When instructions are clearly separated and laid out, users can follow them without making mistakes."

**Comment by rachaelbradley** [comment]
DRAFT Response (Needs approval): Thank you for bringing our attention to this mistake. We have changed the sentence to: They are more likely to make mistakes if they need to remember what they are doing, divide the steps, and track what they have done.

**Comment by martynka** [comment]
This sounds great. Thank you. 
In my view this is resolved and can be closed.

**Comment by rachaelbradley** [comment]
Fixed in 15_February_issues Branch.

**Comment by ruoxiran** [comment]
Fixed in PR #239
