### ISSUE TITLE
4.5.3.2 How it Helps (confusing sentence) 

### ISSUE THREAD

**Issue by martynka** [w3c/coga#192]
Under the "4.5.3.2 How it Helps" section, last sentence in the second paragraph.

The following sentence does not read well. It confuses me. It uses "in other locations" and "in another location". Please rewrite it. 

"They may not know to look in other locations in the user flow or in another location, for example on the homepage, or on a rates page."

Maybe replace the "to look in other locations" with "where to look":
"They may not know where to look,  in the user flow or in another location, for example on the homepage, or on a rates page."

**Comment by jpascalides** [comment]
Thank you for the great find (suggestion). We will fix this issue before publishing!
