### ISSUE TITLE
 comments from PhD student Emma Dixon and  Amanda Lazar 

### ISSUE THREAD

**Issue by lseeman** [w3c/coga#198]
See https://lists.w3.org/Archives/Public/public-coga-comments/2020Jun/0000.html

Below are comments from PhD student Emma Dixon and myself based on our
research and our understanding of advocacy by people with dementia.

   -

   “3.2.2 Pattern: Use a Design that the User is Likely to Recognize and
   Understand” resonates well with our data, where individuals with dementia
   purposefully used older versions of software that had visuales and design
   they understood and recognized. For example, one person with dementia had
   his entire desktop formatted in a 1990s version of Windows, even though he
   was running a current version of the software. It may be worth noting that
   designs should match the mental model of users, which can sometimes
   involves previous versions of software.
   -

   “3.3.3 Pattern: Use a clear and understandable page structure” also
   resonates with our data. We found that people with dementia were able to
   continue to use recipe websites, even though they were visually
   overwhelming, because they all follow the same general structure (the
   author tells their story at the top and how they created the recipe and the
   recipe is at the bottom of the page). So, they were able to scroll right
   past the clutter and get to the recipe.
   -

   “3.4.1 Pattern: Use Clear Words” says that “For other groups, such as
   people living with dementia, learning new terms is not realistic or
   possible. Using uncommon words, that they do not already know, will make
   the content incomprehensible [unable to be understood] and unusable.”
   Recent literature, including our work, argues that learning can continue to
   take place, and this is a particularly important given that  the following
   example talks specifically about someone in the mild stages of dementia.
   Individuals with dementia can learn new things, it just may be much more
   difficult and they have to put in more work than they used to.
   -

   “3.4.10 Pattern: Use White Spacing”, “For those with cognitive
   impairments, white space has been shown to ease reading difficulties and
   improves understanding of content.”: It might be better to say plain
   background instead of white space, as we found that some individuals
   preferred a darker/yellow tinted background to help with eye fatigue.
   -

   5.1 Alison: An Aging User with Mild Cognitive Impairment
   -

      Scenario 2
      -

         Text to speech to read out content she has found she can hear her
         mistakes more easily… this process can make reading web pages
easier and
         less tiring. We have found that audio (e.g., audiobooks) can
be easier than
         written text.
         -

   5.5 Frank: a retired lawyer with dementia:
   -

      In scenario 3,
      -

         "Blocks of text with more white space around them would also be
         helpful so that he is not having to cope with such a mass of text." We
         refer to our point above, that white can be straining for the eyes for
         some- people may need different color backgrounds. But our
findings very
         much affirm the challenges with “masses of text”!
         -

         In the example you give of icons appearing when the groups are
         listed to differentiate the articles about fly fishing and
sea fishing I
         imagine these would be too similar for someone with dementia to
         differentiate. Icons were perceived as confusing for our
participants who
         instead wanted actual pictures representing what the
application was used
         for, because it’s easier to understand a picture than to decipher the
         abstract meaning of icons which often look similar. Past research has
         described issues with icons for people with dementia,
reporting that their
         participants with dementia preferred pictures to icons:
         -

         Kerkhof, Yvonne, Myrna Pelgrum-Keurhorst, Floriana Mangiaracina,
         Ad Bergsma, Guus Vrauwdeunt, Maud Graff, and Rose-Marie Dröes.
         “User-Participatory Development of FindMyApps; a Tool to Help
People with
         Mild Dementia Find Supportive Apps for Self-Management and Meaningful
         Activities.” DIGITAL HEALTH 5 (January 2019): 205520761882294.
         https://doi.org/10.1177/2055207618822942.

   -

   In Scenario 4:

   -

         We are glad that this scenario calls attention to the fact that it
         takes people with dementia a longer time to process
information spoken to
         them. We have also found that people with dementia, when
speaking to voice
         enabled smart home devices, wish the devices took more pauses when
         speaking, giving more time for the person to process the
information and
         their answer, as well as understood their feedback if it’s not phrased
         exactly correct.

**Comment by lseeman** [comment]
adding second email 



All the best

Lisa Seeman

LinkedIn, Twitter







---- On Wed, 22 Jan 2020 08:14:02 +0200 Amanda Erin Lazar <lazar@umd.edu> wrote ----




Hi Rachael and the W3C task force,





I wanted to follow up on my email with Rachael with some thoughts from myself and Emma Dixon, a PhD student leading our project on designing technology for people across the spectrum of dementia. The content below is based on our research as well as research and advocacy by people with dementia.





We are giving these ideas to you below as a first step, but we’d be more than happy to be involved further in any way, or give you more content/edited content/anything else. We are also in contact with some leading members (with and without dementia) of different dementia groups (including Dementia Action Alliance, Dementia Alliance International, and Innovations in Dementia) -  we’d be happy to connect you with these groups or even to work with them ourselves in iterating on any of this. Just please let us know if you see any way we can contribute further!





Best,


Amanda and Emma





--





We have some suggestions of additional dimensions that we have found to be very important for technology use for people with mild to moderate dementia, that could potentially be included in the personas or the section on ICT challenges:


We have found trust of the device or system to be integral. This could translate to the importance of technologies that communicate safe or unsafe sites to visit.


Some of our participants put all of their payments on auto-pay so as not to forget a bill payment and then they just verify their credit card statement.  


Individuals have shared that when a screen is not visible, it is essentially gone for them. Therefore, seeing all possible documents at once is important to reduce confusion as opposed to folders.


Relatedly, spatial representations can be very important for technology use. For example, we have spoken to people that use spatial representations on their desktops as a sort of filing system...





Everything that the document notes for MCI could be said for people with dementia as well, only magnified. 





In terms of the characteristics of dementia, we think that the following points are important to include:


It is great that the report describes the different types of dementia. Though there is tremendous variability even within a condition, it may be important to note that different types of dementia can affect individuals differently and uniquely (Meiland et al. 2017; Scherer et al. 2012). 


Though cognitive changes are the most common changes discussed with dementia, there is an emerging understanding of the other kinds of changes that people experience, that will surely impact their technology use. Many of the points below come from a document (attached) written by a dementia advocate:


Sensitivity to loud and complex environments (overloaded by over stimulus) often with heightened sensitivity to sound


“brain blindness”: where the person has capable vision but the brain is no longer able to process or find the right match for what they’re seeing. 


Contrast is very important because of changes in vision as a result of certain dementias 


Color orientation is not always reliable for people with dementia because they may associate colors differently or not understand what the color is meant to represent 


Avoid busy patterns because they are visually confusing

**Comment by rachaelbradley** [comment]
We appreciate the detailed feedback. We have responded to this by [email ](https://lists.w3.org/Archives/Public/public-coga-comments/2021Mar/0003.html)and created issues 137, 179, and  282 for those pieces that need additional research for the next version.
