### ISSUE TITLE
References to Research item 41 is misformatted

### ISSUE THREAD

**Issue by halindrome** [w3c/coga#2]
Item 41 just shows up as raw HTML.

**Comment by chrisosaurus** [comment]
This appears to have since been fixed in
https://github.com/w3c/coga/commit/9c98d64f1378d3f2b2e98cf3755496c725d4256c#diff-d40b6b6e3fa8671f0665c90da19a7d63L535

This issue should be closed.

**Comment by SteveALee** [comment]
@chrisosaurus  I appreciate the links to the relevant diffs- very useful! Thanks
