### ISSUE TITLE
EO comments: Focus Content Usable on designers, developers, and writers

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#202]
This issue split from #199 -2
Rationale: The length of the document will be daunting to many people. If we can integrate the less technical aspects of the document into the main WAI website, the content can then be focused on the most important target users of designers, developers, and writers. It is doubtful that managers who may care about the business case or UX researchers who may care about the usability content will look for or find the content relevant to them in a document of this kind.
EOWG has also worked hard to avoid covering topics in multiple places on the W3C website. Instead, we seek to put the information in one place, and point to it there from other places where it is relevant. Therefore, we have the following input:
2.1. Appendix: Business Considerations
Remove the Appendix: Business Considerations and The Aging Population as a Market.

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #202](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq202b)

**Comment by rachaelbradley** [comment]
In response to feedback, COGA has shortened and combied this section with the section on policy. While a small part of the content may be redundant we do not expect all of the target audience of Making Content Usable to read other resources. COGA feels this content adds value and we have referenced EO resources as an additional place to read.
