### ISSUE TITLE
EO comments: In the Introduction, add a 1-3 sentences that introduces the relevance for cognitive accessibility and points to the following

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#203]
This issue split from #199  -3
In the Introduction, add a 1-3 sentences that introduces the relevance for cognitive accessibility and points to the following (with their potential updates from the COGA TF):
• The Business Case for Digital Accessibility https://www.w3.org/WAI/business-case/
• Older Users and Web Accessibility https://www.w3.org/WAI/older-users/
In the Introduction, add a 1-3 sentences introduction that points to the following (with their updates from the COGA TF):
• Cognitive and learning disabilities section of Diverse Abilities and Barriers in How People with Disabilities Use the Web https://www.w3.org/WAI/people-use-web/abilities-barriers/#cognitive
• (maybe) Accessibility, Usability, and Inclusion https://www.w3.org/WAI/fundamentals/accessibility-usability-inclusion/
. In the Introduction, add a 1-3 sentences that introduces the relevance for cognitive accessibility and points to the following (with their potential updates from the COGA TF):
• Involving Users in Web Projects for Better, Easier Accessibility https://www.w3.org/WAI/planning/involving-users/
• Involving Users in Evaluating Web Accessibility https://www.w3.org/WAI/test-evaluate/involving-users/
• (and maybe Planning and Managing Web Accessibility https://www.w3.org/WAI/planning-and-managing/ )

**Comment by sharronrush** [comment]
@rachaelbradley @lseeman  Discussion of 11 January led to agreement to add referential sentences in specific sections of _Content Usable_ that point to WAI resources. Would it be acceptable/useful for EO to draft suggested wording for those pointer snetences?

**Comment by rachaelbradley** [comment]
We welcome suggested text and will bring it to the COGA meeting for
discussion once you provide it. Thank you!

**Comment by slhenry** [comment]
From [EOWG Survey Unaddressed Issues [UPDATED question]](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xqqq)
> Several links were added throughout the document. Maybe not all?

**Comment by rachaelbradley** [comment]
We have added the links agreed to in the coordination calls and are happy to explore adding others to our developer resource pages which are outside of the document.
