### ISSUE TITLE
EO comments: 2.2. Background about People with Learning and Cognitive Disabilities and the Web

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#204]
This issue split from #199 -4

2.2. Background about People with Learning and Cognitive Disabilities and the Web
Remove the section 2.2 Background about People with Learning and Cognitive Disabilities and the Web.
- and instead point to existing WAI resources.

**Comment by rachaelbradley** [comment]
The survey responses did not provide clear changes for this particular section. We did address some of the concerns raised in the other sections.
