### ISSUE TITLE
EO comments: 2.3. Building the User into the Development Process and Usability Testing

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#205]
This issue split from #199 -5
Background/Rationale: Most of Section 5 is either already covered in existing WAI resources or was deemed beyond the scope of what W3C/WAI resources should cover. Usability testing is a large topic – whole books are written on it. Including participants with disabilities in usability testing is a big topic – multi-page resources are written on it.
WAI previously decided that it was important to provide a resource on the WAI website that introduced and strongly encouraged including users, e.g., in usability testing -- and that we would briefly introduce the most important points, and not cover other issues or the topic in general. (References: Analysis/Requirements and Changelog for “Involving Users in Web Accessibility Evaluation and Requirements/Analysis and Changelog for Involving Users in Web Development)
The draft of section 5 goes beyond what WAI determined was in W3C’s scope. Additionally, there would be several problems with extending the scope to include this information. For example, Section 5.3 Informed Consent does not use common terminology, does not cover important issues, and has information that some usability professionals might disagree with.
EOWG input:
Remove the sections 2.3 Building the User into the Development Process and remove sections 5.1-5.4 of Usability Testing, Focus Groups and Feedback

**Comment by rachaelbradley** [comment]
The COGA task force feels strongly that there is great value in these sections and decided not to remove them. After discussion with EO chairs and reviewing the detailed comments from a follow up survey with EO, we rewrote the content to address the primary areas of concern such as referring to finding people with cognitive disabilities as "easy",  more clearly framing the section. and linking to the EO resource on this topic.  The updated section can be reviewed at https://raw.githack.com/w3c/coga/consistency_checks/content-usable/index.html#Building_in_the_user

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #205](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq205)

**Comment by rachaelbradley** [comment]
We have added sentences with input from AG to further clarify this section and made one of the scoping questions a note so it further stands out.
