### ISSUE TITLE
EO comments: For sections 5.5.1-5.5.8., make it clearer that they directly relate to a specific one of the “Objectives”

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#206]
This issue split from #199 -6
 For sections 5.5.1-5.5.8., make it clearer that they directly relate to a specific one of the “Objectives”. In the interactive web version, consider providing these in an expandable section on the Objective page.

**Comment by rachaelbradley** [comment]
We tried adding content to make this clearer but found it made reading more difficult. We made sure the section titles map closely to the objective names. (Email sent 10 March 21)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #206](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq18)

**Comment by rachaelbradley** [comment]
Thank you for your comments.  We have added a link to each of the question sets back to the Related Design Objective. This should help clarify the relationship and make navigation easier.
