### ISSUE TITLE
EO comments: Draft idea for section 5 text

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#207]
This issue split from #199 -7
Draft idea for section 5 text:
Section 5: Including users in design and usability testing
It is particularly important to include real people with cognitive and learning disabilities in projects. See the following resources on including people with disabilities (“users”):
• Involving Users in Web Projects for Better, Easier Accessibility:
• describes how involving people with disabilities early in web projects helps
• provides guidance on how to involve users throughout your project, including in planning, designing, and developing
• Involving Users in Evaluating Web Accessibility:
• encourages informal evaluation early
• provides guidance on including people with disabilities in a range of evaluation, including usability testing
These resources encourage you to get a range of people with different disabilities to participate in your project. To understand the range of cognitive and learning disabilities, see the Cognitive and learning disabilities section of Diverse Abilities and Barriers in How People with Disabilities Use the Web.
For developing materials such as consent forms and usability test task descriptions, use the design patterns under Objective 3: Use Clear and Understandable Content.
The following sections provide specific questions to help evaluate if the design patterns under each Objective are achieved.
[content from 5.5.1 – 5.5.8]

**Comment by rachaelbradley** [comment]
We have linked to the EO resource on this topic.  (Email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #207](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq207)

**Comment by rachaelbradley** [comment]
All accepted solution.
