### ISSUE TITLE
EO comments: Appendix B: Considerations for Uptake in Different Contexts and Policies

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#208]
This issue split from #199 -8
Appendix B: Considerations for Uptake in Different Contexts and Policies
Rationale: This section was confusing to most reviewers. First of all, it is lengthy and complex. (The reading grade level is 15-18.) Reviewers noticed significant repetition and lack of focus. Several questioned the relevance of this content to our understood target audience for this document. While the points are valid, the section does not seem to fit. Most reviewers did not find a logical connection to the other content. As a result, EO proposes to strengthen the policy information around COGA issues in the existing WAI resources and to include a shorter statement within this document that points to it.
EOWG input:
Remove Appendix B: Considerations for Uptake in Different Contexts and Policies.

**Comment by rachaelbradley** [comment]
The COGA taskforce feels strongly that there is great value in this section and decided not to remove it however we trimmed it down, combined it with the business section, and linked to the broader EO resource.  You can view the changes at https://raw.githack.com/w3c/coga/consistency_checks/content-usable/index.html#appendix-considerations-for-different-contexts-and-policies  (Email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #208](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq208)

**Comment by rachaelbradley** [comment]
Thank you for your feedback. We have rewritten this section based on feedback from policy makers in COGA and AG and run it by them. We believe this section does add value and have decided to keep it.
