### ISSUE TITLE
EO comments:  Provide the information in a more consumable way than a single TR doc

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#209]
This issue split from #199 -9
Rationale: Some EOWG participants were comfortable having all the Design Guide information in one document. However, others in EO found the size of the document discouraging to explore and hard to navigate. Again there were comments about how the title of “making content usable” was contradicted by the presentation itself and said they would hesitate to pass it along, despite the clear accuracy and value of the content. They felt that their teams would simply not use it in this format, based on input from colleagues they shared the document with.
Additionally, it was very difficult to find specific information and print out just that information.
EOWG has heard the strong preference of the COGA TF to publish as a Working Group Note under w3.org/TR. EOWG understands that preference and does not object. That said, EOWG strongly encourages the information to also be provided in a “web version” that enables users to more easily get to specific information, distribute it to focus on one part at a time, print it, etc.
[1] Has some usability testing findings related to TR docs.
[1] Appendix: W3C WAI website usability testing findings
Participants described the process of using [a TR page] as: “you go to the page, scroll down, scroll down, scroll down, about four or five screens, past all the useless stuff, and then you get to the good stuff. Which is great. But it's always in the middle part of a really, really, really long page.”
Participant quote about W3C TR doc: “…confusing to read. Has great info, there's a lot of it. Not organized in a user friendly way. Really hard to navigate. And find the info I'm looking for. Very text heavy. It's organized like a book with a table of contents, maybe not that way. Maybe should have separate pages for separate things instead of jump down the page.”
Finding 4: Participants' ability to locate task-specific information was significantly hindered by the “front matter” at the start (and close) of the [/TR/] documents…
Participants consistently expressed negative reactions… the initial sections (document's development status and history), were a significant barrier to participants' ability to identify the relevance of the document, comprehend its content, and to navigate within the document.
Participants uniformly stated that whenever they attempted to read a [/TR/] document, they had to first, in one participant's words: “scroll past a ton of irrelevant information about who wrote the document, why, when it was written, and when it was modified.”…
More at: https://www.w3.org/WAI/redesign/ut_report/findings.html#finding4

**Comment by rachaelbradley** [comment]
COGA will continue working with Shadi and Hidde on the interactive web version. We will leave this issue open for the future.  (Email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #209](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq209)

**Comment by rachaelbradley** [comment]
Majority accepted.
