### ISSUE TITLE
EO comments: Specific suggestions to improve usability

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#210]
This issue split from #199 -10
Rationale: There is so much important, useful, and needed information in this research and work. EOWG strongly believes that the current structure creates barriers to a broad use and adoption of its guidance. We suggest that such barriers can be addressed through some basic changes in approach and structure.
4.1. How to use this document
Rewrite section 2.1 “How to Use this Document” to provide guidance for designers, developers, and writers on how to use the document.

**Comment by rachaelbradley** [comment]
We have updated this section and added a link to the appendix some members found more helpful.  (Email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #210](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq210)

**Comment by rachaelbradley** [comment]
The link to Appendix A has been added.
