### ISSUE TITLE
EO comments: Move “Following the advice in this document 

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#211]
This issue split from #199 -11
Move “Following the advice in this document as much as possible will be particularly valuable for Web content and applications that address: … [list]” to the main part of the Introduction or a separate section.

**Comment by rachaelbradley** [comment]
Done (10 email 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #211](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq211)

**Comment by rachaelbradley** [comment]
All accepted solution.
