### ISSUE TITLE
EO comments:  In the Introduction, add a few sentences that more clearly and succinctly provides guidance on using this document in policy and other contexts.

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#212]
This issue split from #199 -12
In the Introduction, add a few sentences that more clearly and succinctly provides guidance on using this document in policy and other contexts. For example, see wording under 4.1. How to use this document below.
 
 Draft idea for section 2.1 1 How to Use this Document:
This document provides information to help website creators make content more usable and accessible for people with cognitive impairments. The high-level objectives outline key design goals that will help people with cognitive impairments. Each objective has associated user needs, stories, personas, and design patterns.
The document is divided into parts that can be used by different groups and in different documents to support content development. For example,
• User needs could be incorporated into requirements specifications
• Design patterns could be used in design guidelines or included in design libraries
• Design patterns can help in developing content guidelines to promote plain language
• User stories and personas can be used to inform design activities such service walkthroughs
The Objectives and Overview section maps the user needs, personas, and patterns together under each objective. This provides a way to understand how to address the objective and why it is important.
Use case: One person skipped the Summary and when right to the “1 How to Use this Document” section. She was then confused what the Objectives were. Another person was also unclear about the Objectives, thinking they were Objectives for this document itself.

**Comment by rachaelbradley** [comment]
We have made this change. Please see https://raw.githack.com/w3c/coga/consistency_checks/content-usable/index.html#how-to-use-this-document (Email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #212](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq212)

**Comment by rachaelbradley** [comment]
The comments on this issue have been addressed. Thank you for your feedback.
