### ISSUE TITLE
EO comments: Summary, Appendix A: Mapping User Needs, Persona and Patterns, Introduction, Objectives

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#213]
This issue split from #199 -13
4.2. Summary, Appendix A: Mapping User Needs, Persona and Patterns, Introduction, Objectives
Use case: Several EO participants has significant difficulty understanding the sections and their relationships, getting an overview of the content, and navigating around the document. When they finally arrived at Appendix A: Mapping, they reacted: “This is great! Now it makes sense! This should be near the top of the document.” In discussing it, we understood that the document has too much information for many of us to process linearly, and having it in the tables helped understand the Objectives and showed how the pieces relate much better for many of us.

**Comment by rachaelbradley** [comment]
COGA experimented with moving the appendix up but it made the document difficult to read. We instead link to it in How to Use this Document. Please see:  https://raw.githack.com/w3c/coga/consistency_checks/content-usable/index.html#how-to-use-this-document (email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #213](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq213)

**Comment by rachaelbradley** [comment]
After trying this suggestion as well as other alternatives, COGA has made the changes that we believe address this to the best of our ability while retaining readability. We believe our users need a quick summary which this provides. We added navigation to the key themes to aid in navigation and referenced Appendix A.
