### ISSUE TITLE
EO comments: Put the Introduction first.

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#214]
This issue split from #199 -14
Put the Introduction first.

**Comment by rachaelbradley** [comment]
We have reworked the introduction per other suggestions. The Abstract, Status and Summary must come before the introduction. The introduction is the first part of the main content. We have added "(Easy to Understand Language)" as part of the Summary header to reduce confusion. (email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #214](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq214)

**Comment by rachaelbradley** [comment]
Some of this request will not work well in the document format and after trying options COGA felt this woudl add confusion. We can explore this further in the Web version.
