### ISSUE TITLE
EO comments: Change “Summary” to something like “Objectives and Overview”.

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#215]
This issue split from #199 -15
Change “Summary” to something like “Objectives and Overview”. Start with a simple explanation of what the Objectives are. Make each objective a heading. Include the explanation that’s currently in the Summary. Then put the table that’s currently under Appendix A.
(Here’s a rough mockup to show the organization that we’re thinking of – although it doesn’t have the first sentence explaining the Objectives.)

![image](https://user-images.githubusercontent.com/6991814/102220158-0c7ddb00-3ea6-11eb-973f-fa33a7373f6d.png)

**Comment by rachaelbradley** [comment]
The summary is the easy read portion of this document.  We have added "(Easy to Understand Language)" as part of the Summary header to reduce confusion. (email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #215](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq215)

**Comment by rachaelbradley** [comment]
After trying this suggestion as well as other alternatives, COGA has made the changes that we believe address this to the best of our ability while retaining readability. We believe our users need a quick summary which this provides.  We added navigation to the key themes to aid in navigation and referenced Appendix A.
