### ISSUE TITLE
EO comments: In the tables, also link the User Stories and Design Patterns.

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#216]
This issue split from #199 -16
Note: Several EOWG participants suggested adding another column to the tables that lists which WCAG SC or Guideline it relates to. We didn’t look at the content enough to figure out the specific relationships and if EO as a group wanted to suggest this.

**Comment by rachaelbradley** [comment]
This is one of the last steps in preparing the document and will be done before publication. (email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #216](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq216)

**Comment by rachaelbradley** [comment]
The links have been added and majority accepted.
