### ISSUE TITLE
EO comments: Icons in Summary

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#217]
This issue split from #199 -17
4.3. Icons in Summary
If you can develop meaningful, intuitive icons that support the concepts, then EOWG suggests that you use them throughout the document to help communicate the relationship of the information. 
(Given EOWG’s struggles with icons, we assume it is best to not try to have them at all.)
 
For example, include the dialog icon in 
Rationale: Unclear icons can be a distraction for users who struggle to understand them. This could be frustrating for some readers. And is counter to the goal of this document to improve accessibility for people with cognitive disabilities, who often need useful images.
(EOWG has spent significant effort to come up with appropriate icons that everyone was comfortable with for several resources, e.g., for abilities, media, tables, a/v, process, business case. We are hesitant that it is feasible to come up with meaningful icons for all of the Objectives, without significant time and effort from the TF and additional input from reviewers.)
EOWG generally liked the format of the summary with icons. However, some participants had issues with some of the icons, particularly 1, 3, 7 and 9.
• (1) Help users understand… -- confusing, seems like steps backwards.
• (2) Help users find… -- OK. conveys “search”, which may or not be what COGA wants to communicate?
• (3) Help users understand with clear text and images… -- cannot figure out what it is trying to communicate.
• (4) Provide support for different ways to understand content. -- complex and confusing, one EOWG participant thought the top right was a clock and didn’t understand the relevance.
• (6) Help users to maintain focus. -- looks like cross-hairs on a target, and could be disturbing for some people.
• (7) Ensure processes do not rely on memory. -- no ideas what this is trying to communicate.
• (9) Support adaptation and personalization. – uncomfortable, feels like things pointed at me from all directions.
• (10) Test with real users! -- OK. communicates older users.

**Comment by jpascalides** [comment]
Thank you for your comment! Work is in progress to update the icons and will be addressed concurrently with issue 231.

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #217](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq217)
