### ISSUE TITLE
EO comments: A minor point is that it would improve readability to have the hanging indent after that images, so text doesn’t wrap under the images.

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#218]
This issue split from #199 -18
A minor point is that it would improve readability to have the hanging indent after that images, so text doesn’t wrap under the images.
3.7, 4.8, A7

**Comment by rachaelbradley** [comment]
This is complete. (email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #218](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq218)

**Comment by rachaelbradley** [comment]
All accept the solution so closing this issue.
