### ISSUE TITLE
EO comments: In the Introduction, add a subheading such as “Not WCAG Requirements” before the paragraph “The Objectives and Patterns presented here provide supplemental guidance beyond the requirements of WCAG….”

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#219]
This issue split from #199 -19
In the Introduction, add a subheading such as “Not WCAG Requirements” before the paragraph “The Objectives and Patterns presented here provide supplemental guidance beyond the requirements of WCAG….”
4.4. Relationship to WCAG
Rationale: Several EO participants missed the information about WCAG altogether. Some didn’t understand it.

**Comment by rachaelbradley** [comment]
After discussion, we addressed this by adding introduction text to clarify each objective rather than changing the objective names.  (email sent 10 March 2021)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #219](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq219)

**Comment by rachaelbradley** [comment]
This is consensus based text and there is no clear direction on what changes to make in the link provided.
