### ISSUE TITLE
EO comments: From the Summary - “I had difficulty understanding objectives 1 and 3.

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#220]
This issue split from #199 -20
4.5. Objectives unclear
Use case: From the Summary - “I had difficulty understanding objectives 1 and 3. They seemed like mangled, but then I concluded objective one talks about conventions (consistent identifiers) and 3 talks more about clear language and signs.”

**Comment by rachaelbradley** [comment]
After discussion, we addressed this by adding introduction text to clarify each objective rather than changing the objective names. (email sent 10 March 2020)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #220](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq220)
