### ISSUE TITLE
EO comments: Headings repetition

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#221]
This issue split from #199 -1
4.6. Headings repetition
Use case, screen reader user: “While reading the table of contents, I find it irritating to read in several sections, titles that have the same text”
Non-screen reader user: “Repeated use of 'Pattern' and 'User Story' adds quite a bit of clutter.”

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #221](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq221)

**Comment by rachaelbradley** [comment]
Based on the acceptance of the majority of responses and that we did change the headings to reduce repetition for screen reader users (which addresses the concerns raised by others) I am closing this issue.
