### ISSUE TITLE
EO comments: Please change some persona names so diverse ethnicities are included.

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#222]
This issue split from #199 -22
4.7. Persona names
Important: Please change some persona names so diverse ethnicities are included.
Use case: “Following our discussion on gender specific documents, when I read user scenarios I have the impression that the users are more female names than male names and wonder if it is author's' intention?”
See also Personas and use cases in the WAI Style Guide

**Comment by rachaelbradley** [comment]
This has been done. (email sent 10 March 2020).

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #222](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq222)

**Comment by rachaelbradley** [comment]
No objections included in responses.
