### ISSUE TITLE
EO comment: 4.8. QA review and copy edit

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#223]
This issue split from #199 -23
4.8. QA review and copy edit
EOWG found some of the wording unnecessarily complex. For example, in one measure, the Introduction gets Reading Grade Level 15 and Appendix B gets Reading Grade Level 18.
For the reputation of this document, WAI, and W3C, it is especially important that this document — which instructs on clear and simple language — also uses clear and simple language.
Additionally, there are several inconsistencies throughout the document, grammar errors, typos, and things that do not meet the WAI Style Guide. Examples:
• Some objectives in the Summary section are not the same as the ones described in the “User stories” and the “Design Guide”.
• “learning and cognitive disabilities”, “cognitive and learning disabilities”
• “Web page”, “Webpage”, “web page”
• “the user”, “the users”, “users” — examples:
• “5.5.1 Does the User Understand What Things Are and How to Use Them?”
“5.5.2 Can Users Find What They Need?”
• “5.5.4 Can Users Avoid Mistakes and Easily Correct Them”
“5.5.5 Can the Users Maintain Focus?”
EOWG recommends a thorough copyedit to:
• simplify the language
• fix grammar errors and typos
• provide consistency within the document and with the WAI Style Guide

**Comment by rachaelbradley** [comment]
We conducted a plain language audit and several editorial reviews of the entire document. (email sent 10 March 2020)

**Comment by slhenry** [comment]
Individual responses from EOWG participants in survey results:
[Acceptance of Issue #223](https://www.w3.org/2002/09/wbs/35532/COGA-accept-response/results#xq223)

**Comment by rachaelbradley** [comment]
Changes to address the inconsistencies raised have been complete. Thank you for pointing those out!
