### ISSUE TITLE
Are you a designer?

### ISSUE THREAD

**Issue by lseeman** [w3c/coga#224]
Are you a designer?

Know one?

If so, please share!

I am a member of a task force working to improve the inclusion of the needs of people with cognitive disabilities in the web accessibility standards. We are currently seeking images to go into the next publication. I have pasted the language of the call below. If you have individuals in your networks that would be interested in receiving this information would you be willing to share this call? I know it is a tight turn around, so I want to be sure the word gets out. While there is no compensation for images, they would have their name listed as a contributor to the document. This document has an international audience.

You can add any images, or links to images in the comments below.

Instead of sharing by email or LinkedIn, you can share this link if you prefer: https://www.w3.org/WAI/GL/task-forces/coga/wiki/Image_language.

I’m happy to answer any questions about this request.

Here’s the official language of the request:

The Cognitive and Learning Disabilities Accessibility Task Force needs help creating images for an upcoming publication that has an international audience. The images will show readers how website designs can improve access to websites. We need two images for each design concept used in our document.

Image 1: a mockup of a website that makes it difficult to use because it does not follow the design concept.
Image 2: a mockup of a website that is easier to use because it follows the design concept.
In the Making Content Usable document (current version, being updated) design concepts are called Objectives.

All images are to be original, and if selected, become property of the W3C. There will be no compensation provided. Artists whose work is selected will be included in the contributors list.

Technical Information

File types: SVG (vector format) preferred.

File should be 1600 px wide.

Please create images with the understanding that some of our readers may:

Magnify the image to better view the details.
View them on different size screens/devices.
Have difficulty perceiving color. They will either view the images as published, or they may use software to change the color schemes. Understanding the images cannot depend on the perception of color.
Only use the alternative text for the image. Please design images that have a clear purpose. This will make it easier for authors to write the alternative text, and for individuals with cognitive disabilities to understand how it is related to its context.
Ready to Help?

If you would like to submit an image for consideration:

Contact John Kirkwood (kirkwood@citymouse.com) and Jennie Delisi (jennie.delisi@state.mn.us) for more information.
We will send you the list of objectives, and links to examples of sites that meet or do not meet these objectives.
Select one or more objectives, and create your designs.
The deadline for submissions is Friday, November 13th, 2020.

A committee will review the submissions and select images for publication. The week of November 23, 2020 the committee will send acceptance emails.

**Comment by deljennie-a11y** [comment]
On November 6th, I replied in LinkedIn to the person requesting more information, and shared the link to this issue.
I then informed John K outside of Github that this occurred.

**Comment by rachaelbradley** [comment]
This activity is complete.
