### ISSUE TITLE
Check that glossary terms work as hyperlinked text

### ISSUE THREAD

**Issue by bruce-usab** [w3c/coga#227]
I don't have any substantive edits to the [glossary](https://raw.githack.com/w3c/coga/add-glossary/content-usable/index.html#glossary).  On the 24 Nov. call, the WG looked at glossary terms in advance of the text being completed, but based on experience with glossary terms, I would recommend a subsequent editorial pass that ensures:
- Glossary terms are used (as much as possible) exactly as phrased in the glossary.
  - There can be variety for plural/singular and verb tense.
- Glossary terms are hyperlinked in the text to their definitions.
- The definitions are worded so that they can be substituted into the text for the terms.
  - Admittedly, this practice can sometimes make the definitions awkward, but it is an important characteristic of normative standards.
  - Notes and examples (following the formal substitution text) can help with clarification.

**Comment by jpascalides** [comment]
Thank you for the great find (suggestion). We will fix this issue before publishing!
