### ISSUE TITLE
COGA icon review suggestions

### ISSUE THREAD

**Issue by r12a** [w3c/coga#231]
1.  Summary
https://www.w3.org/TR/coga-usable/#summary

These are comments on proposed changes at https://docs.google.com/document/d/1aRoYev1aAIHhIq37Itt96ueBwLh5zXMUeJBYxL0MCkQ/edit#

This is related to https://github.com/w3c/i18n-request/issues/148

Our first question is about the intent here, because we see no use of the icons other than in the section that defines them.
Is COGA developing icons that will just be used within their document, or are they proposing to develop icons which can be standardised for use by a general audience?

Here are some specific comments.  These are written as personal comments, but were shared with the i18n WG before sending and there was no disagreement.

**ICON 1 Help users understand what things are and how to use them.**
![Screenshot 2021-01-13 at 16 51 03](https://user-images.githubusercontent.com/4839211/104483042-91e8ce00-55bf-11eb-9ab0-70256c6564ab.png)

I don't find this icon helpful to understand its meaning.  There are other potential issues that are i18n related.  The check mark in some East Asian countries means incorrect; the circle means correct. So this may create a somewhat different meaning from what was intended.

**ICON 3** looks ok, and better than what went before.

**ICON 4 Provide support for different ways to understand content**
Again this doesn't suggest anything to me related to the idea it represents.  I think it's good to move away from use of gestures, though.
 
![Screenshot 2021-01-13 at 16 56 06](https://user-images.githubusercontent.com/4839211/104483768-64505480-55c0-11eb-9cfd-e5b2642dbab6.png)

[I actually prefer the original icon, although i would colour in the small segment in the circle, so that it doesn't look like a clock face.]

**ICONS 5 & 6** i have no comment on, other than to say 2 things:
a. i agree with the concern about the icon that looked like crosshairs.  (This came up on CNN too, just a couple of days ago, in a political context in the USA.)
b. shouldn't the glass of spilled water have an X across it, to indicate that you shouldn't break things?

**ICON 7  Ensure processes do not rely on memory**
![Screenshot 2021-01-13 at 17 01 39](https://user-images.githubusercontent.com/4839211/104484298-0b34f080-55c1-11eb-9b17-b9a0e5d764d3.png)
It's not clear to me whether the habit of tying a string around your finger is recognisable worldwide.  I think that the equivalent in the UK would be to tie a knot in your handkerchief.  For other countries, this may signify nothing, though i suppose it would be understood if the reader figures it out.

Fuqiao doesn't think it's a well-known symbol worldwide. Although he had heard of it, he asked a few friends and they didn’t know...

[I'd be inclined to do something with a picture of a brain...  Just an idea.]

**ICON 10 Support adaptation and personalization**
I think this is an improvement, and i don't know of any i18n related issues.

**Comment by himorin** [comment]
Agree with comment on icon 1.
For icon 7, I don't think string around a finger is global, such that ISO 3864 uses bandage around finger(s) for alerting on injury.

**Comment by lseeman** [comment]
Thank you so much for your comments
Is this icon more clear? 
![image](https://user-images.githubusercontent.com/8376341/105359901-a735ac00-5c00-11eb-9dc5-02cf9e3e3965.png)

**Comment by himorin** [comment]
Not on how icon looks like (or say, asking myself on what this means), but it looks better on a point of telling left side boxes are marked. (I suppose it is better to fill the center white dot in the gray circle, although...)

**Comment by lseeman** [comment]
how about https://www.clipartkey.com/view/ooiJxJ_fingers-clipart-finger-press-finger-pressing-button-clipart/

**Comment by lseeman** [comment]
![image](https://user-images.githubusercontent.com/8376341/106737669-a0a32d80-661f-11eb-8991-1d16902c291a.png)

**Comment by lseeman** [comment]
and for icon 7 
![image](https://user-images.githubusercontent.com/8376341/106737812-ce887200-661f-11eb-83b6-c2666d3576bf.png)

**Comment by r12a** [comment]
@lseeman  Is COGA developing icons that will just be used within their document, or are they proposing to develop icons which can be standardised for use by a general audience?

**Comment by lseeman** [comment]
r12a, sorry i was trying to reply and closed it.... 
we just want them for our document.

**Comment by jpascalides** [comment]
Thank you for the helpful suggestions! We are in the process up updating the icons and the task will be completed before publishing.

**Comment by rachaelbradley** [comment]
The updated icons are at https://raw.githack.com/w3c/coga/consistency_checks/content-usable/index.html

**Comment by r12a** [comment]
I just noticed that the icon at https://raw.githack.com/w3c/coga/consistency_checks/content-usable/index.html#summary-understand has unselectable text in it.  Including bitmap text in an image is generally not a good idea, because it's hard to translate.
