### ISSUE TITLE
Comment from Ceapat (Spain) related to: 2.2 Background about People with Learning and Cognitive Disabilities and the Web

### ISSUE THREAD

**Issue by claraceapat** [w3c/coga#232]
Dear participants,

From Ceapat (www.ceapat.es), I send you this comment related to: 2.2 Background about People with Learning and Cognitive Disabilities and the Web.

It is said: 

. Perception, memory and attention;
. Learning and orientation; and
. Visual, **verbal** or numerical thinking. 

In my opinion, it should be said **language** (instead of verbal). 
The language used on the webs is very important and has enough entity to be mentioned separately in the list. 
In fact, language is taken into account throughout section 4.4.

My proposal is:
. Perception, memory and attention;
. Learning and orientation; 
. **Language**; and
. Visual or numerical thinking. 

Thanks!

**Comment by rachaelbradley** [comment]
Thank you for the great suggestion. We have fixed this issue.

**Comment by claraceapat** [comment]
Thank you very much for considering my proposal.
Best regards from Spain.
