### ISSUE TITLE
Comment from Ceapat (Spain), related to: 4.4.1 Pattern: Use Clear Words

### ISSUE THREAD

**Issue by claraceapat** [w3c/coga#233]
I would add:

Acronyms, acronyms, and abbreviations should be avoided, unless they are the usual way of referring to an item. 
In any case, it is better to incorporate the whole word, to ensure their reading and understanding.
The use of words from another language should also be avoided, unless they are used very frequently and they are well-known.
People with reading difficulties may find it difficult to read these three types of words and therefore do not understand their meaning.

Thank you!

**Comment by jpascalides** [comment]
Thank you for your suggestion. We have adjusted the language to address this topic.

**Comment by rachaelbradley** [comment]
Updates in: https://raw.githack.com/w3c/coga/consistency_checks/content-usable/index.html#use-clear-words-pattern
