### ISSUE TITLE
Comment from Ceapat (Spain) related to: 4.4.3.4 Examples

### ISSUE THREAD

**Issue by claraceapat** [w3c/coga#234]
It is said:
Use: Write clearly. 
Avoid: Do not write unclearly.

From my point of view, they are not examples. I send you a proposal: 

Use: Write clearly. 
Submit your signed application

Avoid: Do not write unclearly.
Do not send the application without signing it.

**Comment by jpascalides** [comment]
Thank you. We have changed the examples!
