### ISSUE TITLE
Comments from Ceapat (Spain). Related to font

### ISSUE THREAD

**Issue by claraceapat** [w3c/coga#237]
Dear collegues,

Regarding the font.

From my experience, it is important not only to use the same font throughout the text, but also to choose a readable font.
The first cognitive process is perception. If a frequent font (arial verdana, etc.) is used, it is easier for the user to recognize the sequence of letters as a word and start the decoding process.
If the word is written in an unusual font, the reader will have to compare each letter of this written word with the mental image of it (the same written word stored in his/her mind) to recognize perceptually that they are both the same word.

This cognitive process is complex and can be easily avoided by using a frequent typeface.
Many designers prefer to use some unusual fonts to innovate or attract attention, but they are difficult to read for people with cognitive disabilities.

Thanks

**Comment by rachaelbradley** [comment]
DRAFT Response: We believe this is a large and evolving topic as well as an important one. We have added fonts to 4.9.4 Pattern: Support a Personalized and Familiar Interface in this version and will open an issue paper on fonts and readability for the next version so we can address it in a more comprehensive way.

**Comment by claraceapat** [comment]
> DRAFT Response: We believe this is a large and evolving topic as well as an important one. We have added fonts to 4.9.4 Pattern: Support a Personalized and Familiar Interface in this version and will open an issue paper on fonts and readability for the next version so we can address it in a more comprehensive way.

Dear

**Comment by claraceapat** [comment]
Dear Rachel,
This is Clara, from Ceapat (www.ceapat.es), (Spain)
Thank you so much for taking into account this topic.
Best regards.

**Comment by lseeman** [comment]
Also note we intend to request a change of fonts from the w3c  for future versions
