### ISSUE TITLE
Under Introduction - bullet points 5 and 6 are duplicates

### ISSUE THREAD

**Issue by inclusiveThinking** [w3c/coga#26]
coga/gap-analysis/index.html

Attitudes and misinformation can also become a barrier to inclusion for people with cognitive disabilities. For example, developers that may feel people with cognitive disabilities are not in their “target audience” and so have no interest in their inclusion. Also, studies of usability often over-sample college students. Thus the results work less well for groups who are not well represented among sub-groups of college students (such the aging population).

**Comment by eric-hind** [comment]
Confirmed that this exists in https://www.w3.org/TR/coga-gap-analysis/ and one can be safely removed.
