### ISSUE TITLE
w3c.github.io/coga/templates link broken

### ISSUE THREAD

**Issue by inclusiveThinking** [w3c/coga#27]
README.md 

https://w3c.github.io/coga/templates

Gives 404

**Comment by chrisosaurus** [comment]
This has since been fixed in
https://github.com/w3c/coga/commit/5c146182c9ee1b67c47a579dec8e9f6326bab349#diff-04c6e90faac2675aa89e2176d2eec7d8

This issue should be closed.

**Comment by SteveALee** [comment]
@chrisosaurus Once again thank you for reporting back to us!
