### ISSUE TITLE
acronym element (tag) is not appropriate

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/coga#314]
The 3rd bullet in [4.4.1.6 Examples](https://www.w3.org/TR/coga-usable/#examples-12) reads:
"Acronyms that are not in common use, are explained the first time they are used, and are in an acronym tag with a title after that."

"an acronym tag" must be "an abbr tag (element)" for HTML. The "acronym" is not appropriate any more.

**Comment by ehind67** [comment]
Thank you for the great find. We will fix this issue before publishing the next version!
