### ISSUE TITLE
Add Contributing.md to this repo

### ISSUE THREAD

**Issue by nschonni** [w3c/coga#36]
I went to make change and wasn't sure without looking whether to start in gh-pages or master. If the process is light, you could just add a blurb in the README.

**Comment by SteveALee** [comment]
Agree.

gh-pages is usually a website but there's no index.html there (probably as we use rawgit urls). I guess the commit comments being 'Generated by TRAVIS-CI ' indicates gh-pages is generated, most like from master :)

**Comment by michael-n-cooper** [comment]
Short answer: use master.

Long answer: I'll look at documenting that.

**Comment by nschonni** [comment]
Fixed in https://github.com/w3c/coga/commit/6b97d73139bf5a8aa74b1a2839ae7a36504964f3
