### ISSUE TITLE
Should I be forking this respository?

### ISSUE THREAD

**Issue by susannkeohane** [w3c/coga#4]
Are we updating the main primary w3/coga OR are we forking the repository, making our updates, then issuing pull request? Also if I fork the repository will it keep in sync automatically or is there a refresh option in this tool?

**Comment by michael-n-cooper** [comment]
People with commit access should normally make edits directly in the 
main repository. Task force approved edits go in the master branch. If 
you wish to propose an edit that may be controversial, use a separate 
branch, that can later be merged in once the issues are worked out. 
There should be no need for anyone with commit access to fork and issue 
pull requests.

Michael
