### ISSUE TITLE
Incorrect heading for ADHD

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#60]
https://github.com/w3c/coga/blob/master/user-research/add.html#L2

I'm pretty sure 'Description' should be 'ADHD' or similar.

**Comment by chrisosaurus** [comment]
It looks like this has since been fixed in
https://github.com/w3c/coga/commit/df8cda6c6e83009ad9f0b27c9cf9665d405054a1

This issue should be closed.

**Comment by SteveALee** [comment]
@chrisosaurus  I agree! Thanks.
