### ISSUE TITLE
The Templates link in the readme is 404

### ISSUE THREAD

**Issue by SteveALee** [w3c/coga#65]

**Comment by JohnRochfordUMMS** [comment]
Steve, I can't find a "Templates" link, nor a "readme" section. Could you be more specific? John

**Comment by SteveALee** [comment]
The README.md. in this repository has a like ending in template. 


Get Outlook for Android






On Mon, Jan 16, 2017 at 8:47 PM +0000, "John Rochford" <notifications@github.com> wrote:












Steve, I can't find a "Templates" link, nor a "readme" section. Could you be more specific? John
