### ISSUE TITLE
coga-gap-analysis: keygen has been removed

### ISSUE THREAD

**Issue by ruoxiran** [w3c/coga#67]
Migrated from [personalization semantics issue 20](https://github.com/w3c/personalization-semantics/issues/20) filed by @plehegar 

In 2.3.2.2 Solutions for security and privacy, keygen is listed as a solution.

However, the latest version of HTML indicates:
[[
keygen has been removed
]]
http://www.w3.org/TR/html52/changes.html#changes-fpwd

**Comment by lseeman** [comment]
Thank you for pointing this out. We think we have addressed this issue. We hope to have a new version by the 17th of July with this fixed and  lots of other issue. (see https://www.w3.org/TR/coga-usable/)

Please feel free to review it again and let us know if you have any more comments!

Thanks again...
The task force
