### ISSUE TITLE
[Gap Analysis] Duplicate Bullet Point in Introduction

### ISSUE THREAD

**Issue by yatil** [w3c/coga#79]
_From @AreaOfAKite on July 1, 2018 19:24_

**URL:**
https://www.w3.org/TR/coga-gap-analysis/#introduction

**Section:**
Introduction

**Issue:**
Bullet #6 is duplicated content from bullet #5
"Attitudes and misinformation can also ..."

_Copied from original issue: w3c/wai-news#4_

**Comment by mbgower** [comment]
@michael-n-cooper 
This issue was closed, but the duplicate bullet is still present in the latest editor's draft. 
As well there are many phrases in the early sections which suggest the document hasn't been carefully reviewed since 2.1 became a Recommendation, such as:

> This information is important to new guidance being added to Web Content Accessibility Guidelines 2.1.
>  Comments are requested by 25 June 2018. 
> The techniques will also lead to a proposal for a WCAG 2.1 (see appendix two).
