### ISSUE TITLE
Possible typo in title and main header of Techniques document

### ISSUE THREAD

**Issue by jfhector** [w3c/coga#87]
The title and main header of the Techniques document has the word 'the' repeated twice in a row:

"Techniques for the The Cognitive and Learning Disabilities Accessibility Task Force (COGA)".

I believe that one of the two 'the' should be deleted.

https://w3c.github.io/coga/techniques/

**Comment by SteveALee** [comment]
Thanks for this. However the document was never published so we are not currently maintaining it. 
See comments on #88 

Please don't let this put you off providing feedback for other documents in future.
