### ISSUE TITLE
Persona/index contains broken links

### ISSUE THREAD

**Issue by chrisosaurus** [w3c/coga#95]
The persona/index.html page contains links to www.aegis-project.eu which no longer appears to be responding to http/https

Example of these broken links
http://www.aegis-project.eu/images/docs/Personas/NiteshHQacc.pdf
http://www.aegis-project.eu/images/docs/Personas/PeterHQacc.pdf
http://www.aegis-project.eu/images/docs/Personas/martaHQacc.pdf
http://www.aegis-project.eu/images/docs/Personas/carlosHQacc.pdf

These links were added in
https://github.com/w3c/coga/commit/fe3db59b
and in turn come from the document
https://docs.google.com/document/d/18bjXRKSW7hT8PQyS2TCzPyo90i55pJamIGSdTrYdBIQ/

**Comment by SteveALee** [comment]
@chrisosaurus thanks very much we'll add this to the backlog for the next release.

**Comment by SteveALee** [comment]
Source - https://github.com/w3c/coga/blob/master/persona/index.html and search for aegis.eu

**Comment by lseeman** [comment]
Thank you for pointing this out.  We will check all links with link checker from https://validator.w3.org/checklink, to address this problem. 
We hope to have a new version by the 17th July at https://www.w3.org/TR/coga-usable/
Please feel free to review it again in a month and let us know if you have any more comments!

Thanks again
