### ISSUE TITLE
Duplicate bullet point

### ISSUE THREAD

**Issue by sheribyrne** [w3c/coga#96]
The third and fourth items are effectively the same

A.4.8 Pattern: Keep text succinct
Use short blocks of text:

Keep paragraphs short. Have only one topic in each paragraph.
Use short sentences. Have only one point per sentence.
Use bulleted or numbered lists.
Use bullets or numbered lists.

**Comment by SteveALee** [comment]
@sheribyrne Great spot, thank you.

**Comment by SteveALee** [comment]
https://github.com/w3c/coga/blob/master/content-usable/design.html#L2434-L2435

**Comment by lseeman** [comment]
Thank you for pointing this out. We have addressed this issue. We hope to have a new version in a few weeks with this fixed and  lots of other issue in the version on the 17th July (see https://www.w3.org/TR/coga-usable/). 

Please feel free to review it again in a month and let us know if you have any more comments!
Thanks again...
